- pages/gettingStarted.md
Had some trouble getting started myself because of this issue. Thought this might be helpful to other Windows users that run into trouble. Now, on to using http://resin.io with my newly provisioned device! :smile:
> Adding additional troubleshooting information to Setting Up Your Device

- pages/gettingStarted-RPI2.md
Added various grammar and spelling corrections. Removed all hyphens after colons in accordance with [The University of Sussex Punctuation Guide](http://www.sussex.ac.uk/informatics/punctuation/colonandsemi/colon).
> Updated gettingStarted-RPI2.md grammar/spelling

- pages/gettingStarted-RPI2.md
In Getting Started with RPI2.
The Internet connection sharing thing could be expanded a bit more, but so far I couldn't find a single webpage  / wikiHow with a tutorial for all OS's.
> Details on SD card and reminder to share connection

- pages/configuration/resin-base-images.md
@shaunmulligan . Please review this!
> Add resin base images page

- pages/installing/gettingStarted-Edison.md
Just removed - mentions of brew.
> remove mentions of brew for edison install

- pages/installing/gettingStarted.md
> fix dockerfile link

- static/css/main.css
Update styles to make SDK docs more readable.
> update h* styles

- navigation.md
- pages/hardware/meta-resin.md
> added meta-resin

- pages/configuration/resin-base-images.md
@shaunmulligan , please review this
> Add links for installed packages on systemd images

- pages/configuration/multi-account.md
- pages/installing/gettingStarted-BBB.md
- pages/installing/gettingStarted-Edison.md
- pages/installing/gettingStarted-Humming.md
- pages/installing/gettingStarted-Nitrogen6x.md
- pages/installing/gettingStarted-Parallella.md
- pages/installing/gettingStarted.md
The format of git endpoint on production has changed? Updated the getting started guides to reflect this.
> fix git endpoints

- pages/configuration/advanced.md
- pages/hardware/i2c-and-spi.md
Signed-off-by: Andrei Gherzan <andrei@resin.io>
> Change the boot partition name to resin-boot

- pages/runtime/supervisor-api.md
To be merged only after resin-supervisor v1.1.0 is deployed.
> Document the Resin Supervisor API

- navigation.md
- pages/installing/gettingStarted-VIA-VAB820.md
> updating VIA links and capitalization

- pages/examples/seed-projects.md
Hello-Scala is based on Hello-Java and is added here for completeness and quicker start.
> Add Hello-Scala

- pages/understanding/understanding-code-deployment.md
> typo in docs

- pages/installing/gettingStarted-BBB.md
Only merge once new flasher behaviour is ready
> updated instructions for new flasher shutdown behaviour

- README.md
- package.json
- Adding README and start script
> Adding README and start script

- navigation.md
- pages/advanced/resources.md
* Added a list of practical posts from the blog.
* Currently in chronological order but will need some sort of categorisation soon.
> add advanced resources

- navigation.md
- pages/runtime/update-strategies.md
(Should only be merged after the env var whitelisting in the API is deployed to production)
> Document the new update strategies feature

- pages/management/devices.md
> Remove websocket warning note

- pages/advanced/resources.md
- pages/installing/gettingStarted-BBB.md
- pages/installing/gettingStarted-Edison.md
- pages/installing/gettingStarted-Humming.md
- pages/installing/gettingStarted-NUC.md
- pages/installing/gettingStarted-Nitrogen6x.md
- pages/installing/gettingStarted-Odroid-C1.md
- pages/installing/gettingStarted-Odroid-XU4.md
- pages/installing/gettingStarted-Parallella.md
- pages/installing/gettingStarted-TS4900.md
- pages/installing/gettingStarted-Zynq-ZC702.md
- pages/installing/gettingStarted.md
- pages/management/applications.md
- pages/management/devices.md
- static/css/main.css
@craig-mulligan @shaunmulligan
> Updated styling

- pages/hardware/devices.md
Although the text states "The Full Raspberry Pi family", I didn't find any info on RPI1 model A, and RP-zero. If these are not supported, it should probably be mentioned here.
> Some clarification on Raspberry Pi generations

- TODO
- pages/getting-started.md
- static/css/main.css
- static/scripts/main.js
- templates/_dynamic-switch.html
- templates/default.html
- templates/getting-started.html
- tools/dynamic-pages.coffee
- tools/util.coffee
Looks slightly raw :) Styling will be applied later.
> Dynamic pages switch

- TODO
- config/index.coffee
- config/links.coffee
- lib/build.coffee
- shared/test/_default.md
- shared/test/artik.md
- shared/test/raspberry-pi+python.md
- shared/whatYouNeed/raspberrypi.md
Don't merge yet, it will be rebased after merging the previous PR.
> Consolidate links

- TODO
- lib/build.coffee
- package.json
- pages/tools/sdk.md
- server/index.coffee
- static/css/main.css
- templates/_breadcrumbs.html
- templates/_nav.html
- templates/default.html
- templates/not-found.html
- tools/fetch-external.sh
* Activate first tab and display title in breadcrumbs for orphaned pages (includes search and 404)
* 404  
* fix Node.js SDK page heading
* doc's h2's in the side nav
> More new docs improvements

- bower.json
- shared/exampleProjects/artik10+nodejs.md
- shared/exampleProjects/artik10+python.md
- shared/exampleProjects/artik5+nodejs.md
- shared/exampleProjects/artik5+python.md
- shared/exampleProjects/generic/rpi-nodejs.md
- shared/exampleProjects/generic/rpi-python.md
- shared/exampleProjects/raspberrypi2+nodejs.md
- shared/exampleProjects/raspberrypi2+python.md
- shared/exampleProjects/raspberrypi3+nodejs.md
- shared/exampleProjects/raspberrypi3+python.md
- shared/icon.md
- templates/default.html
* add github icon set
* add icon partial
* add github icon next to repo links
@emirotin @shaunmulligan
> add icon partial

- README.md
- config/links.coffee
- pages/configuration/advanced.md
- pages/deployment/deployment.md
- pages/examples/projects.md
- pages/management/applications.md
- pages/management/devices.md
- pages/management/env-vars.md
- pages/management/preferences.md
- pages/runtime/runtime.md
- pages/understanding/understanding-code-deployment.md
Commit description contains explanation about my edits.
> Fixes & additions to the docs

- pages/hardware/i2c-and-spi.md
- shared/whatYouNeed/artik10.md
> Minor issues p1

- config/index.coffee
- templates/default.html
Along the way for #259, the minimal change that already improves things.
Incorporated comment on #260.
> Minimal viable shareability updates v2

- config/index.coffee
- templates/default.html
Set it through `BASE_URL` environmental variable.
> Template changes introducing base URL

- .gitignore
- Dockerfile
- README.md
- package.json
@emirotin, As a step towards hosting this with Docker, I've created a Dockerfile. Can you take a look and see how it looks? Closes #250.
> feat(docker): Add Dockerfile

- config/dictionaries/device.json
- shared/crossCompilation/rust.md
Notified by johnboy14 in public chat that this has changed
> updated linker

- pages/configuration/advanced.md
- pages/hardware/i2c-and-spi.md
> documented uart

- bower.json
> headroom-js: previous module was merged into new one, bump version

- config/navigation.txt
- config/redirects.txt
- pages/deployment/network.md
- pages/installing/gettingStarted-BBB.md
- pages/installing/gettingStarted-Edison.md
- pages/installing/gettingStarted-Humming.md
- pages/installing/gettingStarted-NUC.md
- pages/installing/gettingStarted-Nitrogen6x.md
- pages/installing/gettingStarted-Odroid-C1.md
- pages/installing/gettingStarted-Odroid-XU4.md
- pages/installing/gettingStarted-Parallella.md
- pages/installing/gettingStarted-RPi.md
- pages/installing/gettingStarted-TS4900.md
- pages/installing/gettingStarted-VIA-VAB820.md
- pages/installing/gettingStarted-Zynq-ZC702.md
- pages/troubleshooting/error.md
- pages/troubleshooting/faq.md
- shared/getDeviceOnDash/raspberrypi.md
- shared/getDeviceOnDash/raspberrypi2.md
- shared/getDeviceOnDash/raspberrypi3.md
> rename network setup page

- pages/runtime/runtime.md
Add notes to the tips&tricks section of the container runtime docs, to show how to mount external storage without init system, in systemd, and in OpenRC.
> add information on mounting external storage media within applications

- config/dictionaries/language.json
- shared/crossCompilation/go.md
- shared/deployingCode/go.md
- shared/diveIntoCode/go.md
- shared/introduction/go.md
- static/img/language/go.svg
Quick Golang getting started guide. Please merge asap as I want to reference from my ENM read me.
> Golang getting started

- pages/getting-started.md
The only one I'm not sure about is **Enjoy Resinifying All the Things!** Based on our [burgeoning style manual](https://github.com/resin-io/docs/pull/345), this would be **Enjoy resinifying All the Things!**
> Standardizing capitalization

- pages/runtime/update-strategies.md
> Add docs for the 'delete-then-download' update strategy

- shared/deployingCode/cpp.md
- shared/deployingCode/go.md
- shared/deployingCode/nodejs.md
- shared/deployingCode/python.md
- shared/deployingCode/rust.md
> clarify the use of git force to replace the whole source tree

- pages/runtime/data-api.md
- shared/getDeviceOnDash/artik710.md
- shared/selectNetworkConfig/artik710.md
@craig-mulligan made your fixes here, since I had merged the other branch already
> fix minor typos, etc for ARTIk 710

- README.md
Starting a rough style manual. This PR sprung from a conversation in r/process. 
I’ll leave a TBD spot for a default style manual, so bring on your opinions! (Assuming this is a good place to have that conversation, associated with the document that is changing.) 
Feasible options include standard journalist choices like [Chicago Manual of Style](http://www.chicagomanualofstyle.org/home.html) or the [AP Style Guide](https://www.apstylebook.com/). Upside is they're widely adopted, downside is they require payment/logins. There's a newer Mailchimp (forkable) [styleguide](http://styleguide.mailchimp.com/). Upsides seem to be the forkability/OSS and focus on Internet communications (and being a SaaS company), and I can't think of a downside. 😁
> Adding the beginnings of a style manual

- pages/deployment/network.md
- pages/troubleshooting/error.md
Connects to #357
Might need some cross-check for validity of the information.
> Update info on `config.json` location

- pages/installing/gettingStarted-Humming.md
Temporary solution to add Etcher to the getting started, before moving all outstanding boards to parametric content
> add Etcher to Humming board getting started

- shared/flashingOsToBootMedia/_default.md
> update Etcher homepage link

- shared/crossCompilation/go.md
- shared/diveIntoCode/go.md
> Replaced josephroberts with resin-io-projects

- pages/deployment/build-optimisation.md
This decreases build times in some scenarios.
> Add section on running tasks in the background

- pages/examples/seed-projects.md
Remove master-arm instructions, and go specific instructions.
> rm mentions of master-arm

- pages/troubleshooting/faq.md
Removing the most glaring issues highlighted, plus some typographic
adjustments. No new content has been added yet.
> [issue #386] FAQ are updated

- pages/runtime/runtime.md
> [Issue #390] making dbus examples referencable

- pages/runtime/runtime.md
> Added information about new supervisor environment vars.

- config/navigation.txt
- pages/runtime/time.md
Adding the comments gathered over different support requests, connects to #393
> [issue #393]: add info regarding NTP & time management

- shared/general/container-ssh.md
https://gitter.im/resin-io/chat?at=57be336fce157d1b57a19e82
> now works with resin env vars containing spaces

- pages/tools/cli.md
- pages/tools/python-sdk.md
- pages/tools/sdk.md
> Add resin cli and sdk (js/python) docs

- pages/troubleshooting/error.md
Took me a long time to figure out what was going wrong, this would have helped.
> Update help docs for wrong device type

- shared/sshKey/add/_default.md
> update link to github ssh key generation docs

- config/redirects.txt
Reported here: https://www.flowdock.com/app/rulemotion/resin-frontend/threads/d67HySDyrbn5HENvXSuslvtBeTu
> redirect old cli link

- config/navigation.txt
- pages/runtime/update-locking.md
- tools/fetch-external.sh
> Add update locking info back to the docs

- config/navigation.txt
- pages/introduction.md
- pages/runtime/resin-base-images.md
> Not actually a wiki

- pages/installing/gettingStarted-Edison.md
> update Intel Edison links

- pages/runtime/runtime.md
> adding dbus system bus address information for both resinOS 1.x and 2.x

- pages/runtime/update-locking.md
- pages/tools/sdk.md
> update supervisor update locking and SDK docs

- pages/runtime/supervisor-api.md
- pages/tools/cli.md
- pages/tools/sdk.md
Update the docs with latest CLI, SDK and supervisor API docs.
This includes the new build and deploy commands implemented by @CameronDiver
> pull in latest CLI, SDK and Supervisor docs

- pages/runtime/data-api.md
> Document /whoami endpoint

- tools/prepare.sh
> Make npm run in the docker build

- static/css/Montserrat.css
bug found when testing over ssl. 
> Fix protocal mismatch for font requests

- pages/runtime/runtime.md
- pages/runtime/time.md
Questions that came in to prompt these clarifications: https://forums.resin.io/t/time-synchronization/941
> Update time related notes based on questions in the forums.

- shared/networking/2.0.0.md
> Instructions for setting reg domain in config.json

- config/dictionaries/device.json
- config/navigation.txt
- shared/getDeviceOnDash/jetson-tx2.md
- shared/getDeviceOnDash/raspberrypi3.md
- shared/whatYouNeed/jetson-tx2.md
> Getting started updates for Jetson TX2

- pages/installing/gettingStarted-TS4900.md
Fixes #553
Also fix a couple of minor typos
> Fix image link

- pages/troubleshooting/error.md
- shared/networking/2.0.0.md
A few updates to address issues #479, #485, #513, and #535.
> Updates to network-related documentation

- pages/development/local-mode.md
> Change wording for description of local mode requirements

- pages/devicetypes.md
> add title to Device Types page

- pages/development/local-mode.md
> Make a list with all Local Mode requirements

- pages/hardware/i2c-and-spi.md
Typo correction - I assume this is what was meant.
> Typo correction

- pages/updates/self-service.md
- pages/updates/update-process.md
Added a small note about supervisor updates in the "Running an update" section. Also included some formatting changes (don't bold resinOS and resin.io).
> Add note about supervisor updates

- .resinci.yml
- Makefile
- package.json
Signed-off-by: Jack Brown <jack@resin.io>
> ci: Switch to ResinCI

- pages/reference/supervisor/bandwidth-reduction.md
Signed-off-by: Pagan Gazzard <page@resin.io>
> Update the poll interval values to specify 10 minutes

- config/index.coffee
Signed-off-by: Jack Brown <jack@resin.io>
> Fix header links after rename

- config/links.coffee
change-type: minor
Signed-off-by: Shaun Mulligan <switchflip.shaun@gmail.com>
> fix: use old github org names until renamed

- README.md
- config/dictionaries/device.json
- config/dictionaries/language.json
- config/index.coffee
- config/links.coffee
- config/names.coffee
- package-lock.json
- pages/faq/troubleshooting/faq.md
- pages/learn/deploy/release-strategy/update-locking.md
- pages/learn/develop/dockerfile.md
- pages/learn/develop/integrations/artik.md
- pages/learn/develop/integrations/aws.md
- pages/learn/develop/local-mode.md
- pages/learn/manage/actions.md
- pages/learn/more/examples/projects.md
- pages/learn/welcome/production-plan.md
- pages/reference/cli.md
- pages/reference/sdk/node-sdk.md
- pages/reference/sdk/python-sdk.md
- shared/getting-started/exampleProjects/generic/rpi-nodejs.md
- shared/getting-started/exampleProjects/raspberry-pi2+nodejs.md
- shared/getting-started/exampleProjects/raspberrypi3+nodejs.md
- shared/network/1.x.md
- shared/network/2.x.md
Fixed a lot of link issues, changed URL variable from www.balena.io to balena.io and other doc links.
Signed-off-by: Daniel Andrade daniel@balena.io
> Daniel docs review 2018

- README.md
- config/names.coffee
- package.json
- shared/network/1.x.md
- shared/network/2.x.md
> Remove pubnub, update dashboard domain fixes #935

- config/dictionaries/device.json
- config/dictionaries/language.json
- templates/_dynamic-switch.html
Signed-off-by: Shaun Mulligan <switchflip.shaun@gmail.com>
> fix: update dictionaries so both icons and images work everywhere

- templates/devices.html
Rework of https://github.com/balena-io/docs/pull/909
> Add sales contact details to supported devices

- config/dictionaries/resource.json
> Fix move device example

- pages/learn/develop/runtime.md
Connects-to: #991
Signed-off-by: Heds Simons <heds@balena.io>
> hostcomms: Ensure labels are specified for MC use

- static/css/main.css
> responsiveness: Make the content easier to read on mobile screens

- package-lock.json
- package.json
- static/css/menu-top.css
- static/scripts/main.js
- templates/_top-menu.html
> mobile:  Fix mobile navigation, search and logo rendering

- templates/_algolia.html
- templates/_search-form-mobile.html
- templates/_top-menu.html
> search: Fix desktop search

- pages/reference/base-images/base-images.md
Add minor changes to keep the document consistent as well
Signed-off-by: Firat Gelbal firat@balena.io
> Fix typos on base-images.md

- templates/_nav-mobile.html
- templates/_top-menu.html
> nav: Fix submenu tabs navigation

- shared/general/container-ssh.md
Signed-off-by: Daniel Andarde daniel@balena.io
> Fix balena-openssh link from projects to playground.

- pages/learn/develop/local-mode.md
Signed-off-by: Shaun Mulligan <shaun@balena.io>
> local-mode.md: Change to using balena push

- webpack.config.js
> webpack: Fix font-files path

- pages/learn/welcome/introduction.md
> Add public roadmap in Welcome page

- README.md
- package-lock.json
- pages/learn/deploy/release-strategy/update-locking.md
- pages/learn/develop/dockerfile.md
- pages/learn/develop/hardware/i2c-and-spi.md
- pages/learn/develop/integrations/artik.md
- pages/learn/develop/integrations/aws.md
- pages/learn/develop/integrations/bluemix.md
- pages/reference/cli.md
- pages/reference/sdk/node-sdk.md
- pages/reference/sdk/python-sdk.md
- pages/reference/supervisor/supervisor-api.md
- shared/general/deviceTypeNames.md
Also fix up broken references to $names.base.lib (should be
$names.base_images.lib)
The rest of the changes were pulled in automatically as part of a build (can revert if necessary).
Signed-off-by: Matthew McGinn <mamcgi@gmail.com>
> Fix up broken deviceTypeNames link for Nitrogen 6X

- shared/getting-started/deployingCode/nodejs.md
Signed-off-by: Trevor Sullivan [trevor@balena.io](mailto:trevor@balena.io)
> Updated verbiage for node.js getting started guide

- package-lock.json
- package.json
- pages/reference/cli.md
- pages/reference/sdk/python-sdk.md
Signed-off-by: Paulo Castro <paulo@balena.io>
> Update CLI and Python SDK reference docs (run prepare.sh)

- pages/learn/develop/runtime.md
> Remove BALENA_APP_RELEASE from the sample output

- shared/getting-started/whatYouNeed/artik10.md
- shared/getting-started/whatYouNeed/artik530.md
- shared/getting-started/whatYouNeed/artik533s.md
- shared/getting-started/whatYouNeed/asus-tinker-board-s.md
- shared/getting-started/whatYouNeed/asus-tinker-board.md
- shared/getting-started/whatYouNeed/bananapi-m1-plus.md
- shared/getting-started/whatYouNeed/beaglebone-black.md
- shared/getting-started/whatYouNeed/fincm3.md
- shared/getting-started/whatYouNeed/iot2000.md
- shared/getting-started/whatYouNeed/kitra710.md
- shared/getting-started/whatYouNeed/nitrogen6x.md
- shared/getting-started/whatYouNeed/odroid-c1.md
- shared/getting-started/whatYouNeed/odroid-xu4.md
- shared/getting-started/whatYouNeed/orangepi-plus2.md
- shared/getting-started/whatYouNeed/raspberry-pi.md
- shared/getting-started/whatYouNeed/raspberry-pi2.md
- shared/getting-started/whatYouNeed/raspberrypi3.md
- shared/getting-started/whatYouNeed/revpi-core-3.md
- shared/getting-started/whatYouNeed/ts4900.md
- shared/getting-started/whatYouNeed/up-board.md
- shared/getting-started/whatYouNeed/var-som-mx6.md
> Fix "what you need" markdown rendering issue

- config/names.coffee
- pages/faq/troubleshooting/faq.md
- pages/faq/troubleshooting/troubleshooting.md
- pages/reference/OS/updates/self-service.md
- shared/general/host-ssh.md
- shared/getting-started/getDeviceOnDash/intel-edison.md
- shared/getting-started/getDeviceOnDash/ts4900.md
- shared/getting-started/usingSupport/_default.md
- shared/network/1.x.md
Connects-to: #1026
In Heroku
edit: The above ENV_VAR should be `DOMAIN_FORUMS` instead. Fixed.
> Fix forums redirects

- pages/reference/supervisor/docker-compose.md
Signed-off-by: Matthew McGinn <mamcgi@gmail.com>
> Fix up small typo, remove trailing spaces

- shared/network/2.x.md
Remove spurious trailing spaces
Signed-off-by: Matthew McGinn <mamcgi@gmail.com>
> Add back missing "nm-setting-ref" link

- pages/learn/manage/configuration.md
* clarified that these are only *some* of the variables which can be configured
* added link to raspberry pi docs for config.txt
> small tweak to rpi config.txt var list section

- pages/learn/manage/actions.md
Signed-off-by: Trevor Sullivan <trevor@balena.io>
> Adding documentation about transferring application ownership

- README.md
Signed-off-by: Shaun Mulligan <shaun@balena.io>
> readme.md: Update commit guidelines

- shared/network/2.x.md
Signed-off-by: Shaun Mulligan <shaun@balena.io>
> networking: Update tested modems list

- pages/reference/supervisor/bandwidth-reduction.md
> docs: fix up bandwidth reduction formatting

- config/dictionaries/os_version.json
- pages/reference/OS/advanced.md
- shared/getting-started/getDeviceOnDash/bananapi-m1-plus.md
> config: update 'resinOS 2.x' to 'balenaOS 2.x'

- .resinci.yml
- package.json
* in testing on the CI servers
* in Heroku
Signed-off-by: Gergely Imreh <gergely@balena.io>
> Node version set to 10

- pages/reference/supervisor/docker-compose.md
This should help looking up the meaning and use of the different fields.
Signed-off-by: Gergely Imreh <gergely@balena.io>
> docker-compose: link to the relevant entries in the docker compose docs

- Dockerfile.bindmount
- README.md
- pages/reference/cli.md
- pages/reference/sdk/node-sdk.md
- pages/reference/supervisor/supervisor-api.md
> Fetch external docs and add Dockerfile.bindmount for macOS users

- pages/learn/manage/configuration.md
> os: fix up broken anchor link for advanced boot settings

- shared/overview/2.x.md
> docs: conform to standard capitalization

- pages/learn/develop/local-mode.md
- shared/overview/2.x.md
>  balenaCLI: local push/scan have been deprecated

- shared/overview/2.x.md
> image-partition-layout: fix up confusing wording

- config/dictionaries/device.json
- config/links.coffee
- pages/learn/develop/hardware/gpio.md
- pages/learn/develop/hardware/i2c-and-spi.md
- pages/learn/develop/integrations/artik.md
- pages/learn/develop/integrations/azure.md
- pages/learn/develop/integrations/bluemix.md
- pages/learn/more/examples/projects.md
- pages/learn/more/examples/seed-projects.md
- pages/learn/more/examples/snippets.md
- pages/learn/welcome/production-plan.md
- pages/reference/OS/meta-balena.md
- pages/reference/OS/updates/migrate-to-2.0.md
- pages/reference/OS/updates/update-process.md
- pages/reference/supervisor/docker-compose.md
- pages/reference/supervisor/supervisor-api.md
- shared/general/deviceTypeNames.md
- shared/getting-started/exampleProjects/beaglebone-black+nodejs.md
- shared/getting-started/exampleProjects/generic/rpi-nodejs.md
- shared/getting-started/whatYouNeed/bananapi-m1-plus.md
- shared/getting-started/whatYouNeed/intel-nuc.md
- shared/getting-started/whatYouNeed/odroid-c1.md
- shared/getting-started/whatYouNeed/odroid-xu4.md
- shared/getting-started/whatYouNeed/orangepi-plus2.md
- shared/getting-started/whatYouNeed/raspberry-pi.md
- shared/getting-started/whatYouNeed/raspberry-pi2.md
- shared/getting-started/whatYouNeed/raspberrypi3.md
- shared/getting-started/whatYouNeed/up-board.md
- shared/overview/2.x.md
Depends-on: https://github.com/balena-io/balena-sdk/pull/720
> links: fix up broken hyperlinks en-masse

- pages/faq/troubleshooting/troubleshooting.md
- pages/learn/develop/integrations/azure.md
Signed-off-by: Michael Angelos Simos <michalis@balena.io>
> Fix dashboard_domain references

- .github/CODEOWNERS
- CONTRIBUTING.md
> meta: add CODEOWNERS and CONTRIBUTING.md

- pages/learn/develop/local-mode.md
> localMode: mention that volumes will also be destroyed

- config/names.coffee
- config/navigation.txt
- pages/learn/more/collected-data.md
Supervisor data obtained with https://github.com/balena-io/balena-supervisor/pull/1040
> docs: Add info on collected data

- shared/getting-started/deployingCode/cpp.md
- shared/getting-started/deployingCode/nodejs.md
- shared/getting-started/deployingCode/python.md
> docs: properly format "here on Github" link

- shared/overview/2.x.md
> balena 2.x: clean up formatting & grammar

- pages/learn/deploy/release-strategy/update-locking.md
> docs: update broken supervisor lock override link

- pages/reference/base-images/base-images.md
> baseImages: Update latest stack versions

- shared/general/persistent-storage.md
Signed-off-by: Cameron Diver <cameron@balena.io>
> Add documentation about supervisor volume cleanup operation

- pages/learn/develop/local-mode.md
> docs: remove references to `local ssh`

- pages/learn/develop/runtime.md
- pages/reference/base-images/base-images.md
- shared/network/2.x.md
- shared/overview/2.x.md
> host OS: standardize on "host OS" (rather than hostOS)

- config/dictionaries/device.json
Connects-to: https://github.com/balena-io/docs/issues/971
> device list: alphabetize by name to match the dashboard

- templates/_track.html
See also https://github.com/balena-io/assets/pull/75
> Fix mixpanel proxy configuration

- pages/reference/OS/updates/self-service.md
- pages/reference/OS/updates/update-process.md
> hup: fix up formatting and nomenclature

- config/navigation.txt
- pages/reference/diagnostics.md
until the device-diagnostics repo is open-sourced, these docs need to be pulled in manually
Connects-to: https://github.com/balena-io/device-diagnostics/pull/113
Connects-to: https://github.com/balena-io/device-diagnostics/issues/110
> diagnostics: pull in checks docs manually for initial release

- shared/general/deviceTypeNames.md
> Add 64-bit Pi 3 and Pi 4 machine names

- templates/_track.html
> Pass anonymous tracking ID to dashboard URLs

- pages/reference/diagnostics.md
Depends-on: https://github.com/balena-io/resin-proxy/pull/410
> diagnostics: update check definitions to 4.8.0

- pages/learn/welcome/security.md
Changed OpenID Connect URL reference 
> Changed OpenID Connect URL reference

- .github/CODEOWNERS
> Adding new codeowners

- shared/getting-started/balenaCliAuth/_default.md
- shared/getting-started/createAnApp/_default.md
- shared/getting-started/deployingCode/cpp.md
- shared/getting-started/deployingCode/go.md
- shared/getting-started/deployingCode/haskell.md
- shared/getting-started/deployingCode/nodejs.md
- shared/getting-started/deployingCode/python.md
- shared/getting-started/deployingCode/rust.md
> Tidy getting started changes

- shared/getting-started/balenaCliAuth/_default.md
Signed-off-by: Paulo Castro <paulo@balena.io>
> Update CLI npm installation note in Getting Started guide

- shared/getting-started/whatYouNeed/raspberry-pi2.md
- shared/getting-started/whatYouNeed/raspberrypi3.md
- shared/getting-started/whatYouNeed/raspberrypi4.md
Signed-off-by: Paulo Castro <paulo@balena.io>
> Fix USB cable requirement for RPi 4 (USB-C instead of micro USB)

- pages/learn/deploy/release-strategy/update-locking.md
- pages/reference/cli.md
- pages/reference/sdk/node-sdk.md
- pages/reference/supervisor/docker-compose.md
- shared/network/2.x.md
Note there are 3 commits (review them separately...):
* Fetch external docs (./tools/fetch-external.sh)
* Update "docker-compose.yml fields" docs re 'build' (git URLs not supported)
* Add note on Google DNS (8.8.8.8) to Network Requirements section
Resolves: #1122
Connects-to: balena-io-modules/resin-multibuild/issues/66
> Update "docker-compose fields" and Network Requirements docs

- README.md
- config/doxx.coffee
- config/index.coffee
- config/links.coffee
- templates/default.html
> Allow improve this doc for external repos

- config/navigation.txt
- pages/learn/more/masterclass.md
> Adding page for masterclass links

- shared/network/2.x.md
Signed-off-by: Michael Angelos Simos <michalis@balena.io>
> Network Requirements: Fix dnsServer setting link

- pages/faq/troubleshooting/faq.md
> docs: Removing container port forwarding FAQs

- pages/reference/supervisor/docker-compose.md
> Note that var substitution isn't supported for compose

- shared/getting-started/balenaPush/_default.md
- shared/getting-started/deployingCode/cpp.md
- shared/getting-started/deployingCode/go.md
- shared/getting-started/deployingCode/haskell.md
- shared/getting-started/deployingCode/nodejs.md
- shared/getting-started/deployingCode/python.md
- shared/getting-started/deployingCode/rust.md
> Clarifying open terminal in project directory

- config/redirects.txt
> Add supervisor API redirect

- shared/network/2.x.md
> docs: Updating dnsServers reference

- pages/reference/OS/meta-balena.md
- pages/reference/hardware/versioning.md
- shared/getting-started/getDeviceOnDash/var-som-mx6.md
- shared/network/2.x.md
> balena-os: replace all references to balena-os project with variable

- shared/network/2.x.md
> networking: describe NM's connectivity checking feature

- pages/reference/OS/updates/self-service.md
> capitalization: make "Update balenaOS" standard in update docs

- pages/learn/deploy/delta.md
- pages/learn/welcome/primer.md
> docs: Deltas enabled by default

- pages/learn/develop/dockerfile.md
- pages/reference/supervisor/docker-compose.md
- shared/general/labels-version-note.md
- shared/general/labels.md
> docs: Update label names for balena

- pages/learn/develop/dockerfile.md
- pages/learn/develop/hardware/i2c-and-spi.md
- pages/learn/develop/integrations/aws.md
- pages/learn/more/examples/snippets.md
- pages/reference/base-images/base-images.md
Thanks, @lurch ref https://github.com/balena-io/docs/pull/1027#issuecomment-562198838
> docs: Updating GitHub playground links for variables

- pages/learn/develop/dockerfile.md
Systemd is no longer supported in the base images, see: https://www.balena.io/docs/reference/base-images/base-images/#major-changes
> Remove outdated section about systemd

- pages/learn/more/examples/seed-projects.md
A quick purge of very outdated projects that no longer build.  Can assess requirements for additional projects/languages but this removes very outdated information ref https://www.flowdock.com/app/rulemotion/i-docs/threads/MD6TGeNRQ5ts5JUzpgvARb_3Qmh
> docs: Updating seed projects

- pages/learn/develop/runtime.md
> docs: Updating networking documentation

- pages/learn/deploy/delta.md
- pages/learn/welcome/primer.md
This reverts commit 01074cf357da96ae0ccfe973e263f431d0bb5a1d.
> revert: "docs: Deltas enabled by default"

- pages/faq/troubleshooting/troubleshooting.md
> troubleshooting: mention PWR LED indicating undervoltage

- config/dictionaries/device.json
- shared/getting-started/whatYouNeed/artik10.md
- shared/getting-started/whatYouNeed/artik530.md
- shared/getting-started/whatYouNeed/artik533s.md
- shared/getting-started/whatYouNeed/artik710.md
Closes #1265 
Connects-to: 1265
> docs: Remove Artik links

- pages/learn/more/resources.md
> docs: Remove outdated blog link

- package-lock.json
- package.json
Cherry-picked these individual commits into a single PR to save rebasing after each one.
I'm unsure of how we would properly test this. I've pushed this to staging and tested locally and see no ill-effects https://www.balena-staging.io/docs/learn/getting-started/raspberrypi3/nodejs/
> deps: Updating dependabot dependencies

- pages/reference/OS/time.md
> docs: Clarifying versions for chrony and timestampd

- shared/getting-started/whatYouNeed/hummingboard.md
- shared/getting-started/whatYouNeed/intel-nuc.md
- shared/getting-started/whatYouNeed/nitrogen6x.md
Closes: #1289 
Connects-to: #1289
> Fix links to WiFi adapters on Getting Started

- pages/learn/more/collected-data.md
Closes #1286 
Connects-to: #1286 
> docs: Clarifying analytics detail

- pages/learn/welcome/production-plan.md
Closes #1281 
Connects-to: #1281
> docs: Updating production plan for masterclass and preregistering

- templates/_top-menu.html
Closes #1293 
Connects-to: #1293
> meta: Fix logo acts as home link

- pages/faq/troubleshooting/faq.md
- pages/learn/more/examples/projects.md
- shared/network/1.x.md
- shared/network/2.x.md
> meta: Americanize "synchronization", fix up small capitalization issues

- config/dictionaries/resource.json
- shared/apiGeneral/calls.md
- shared/apiGeneral/versioning.md
> docs: Bumping API version to v5

- config/navigation.txt
- pages/reference/OS/configuration.md
- shared/general/config-json-fields.md
> docs: Adding config.json documentation

- pages/reference/OS/advanced.md
Related to https://github.com/balena-io/balena-api/issues/2348
> config: Update disable-splash config.txt option

- config/navigation.txt
- pages/learn/develop/container-contracts.md
> Adding container contract documentation

- shared/network/2.x.md
> typo: is -> are to match noun

- config/links.coffee
- pages/learn/deploy/deployment.md
- pages/learn/develop/hardware/i2c-and-spi.md
- pages/learn/develop/integrations/aws.md
- pages/learn/develop/integrations/azure.md
- pages/learn/develop/integrations/bluemix.md
- pages/learn/develop/multicontainer.md
- pages/learn/develop/runtime.md
- pages/learn/more/examples/projects.md
- pages/learn/more/examples/seed-projects.md
- pages/learn/more/examples/snippets.md
- pages/learn/welcome/production-plan.md
- shared/deployment/secrets/_default.md
- shared/getting-started/deployingCode/cpp.md
- shared/getting-started/deployingCode/go.md
- shared/getting-started/deployingCode/haskell.md
- shared/getting-started/deployingCode/nodejs.md
- shared/getting-started/deployingCode/python.md
- shared/getting-started/deployingCode/rust.md
- shared/getting-started/exampleProjects/artik10+nodejs.md
- shared/getting-started/exampleProjects/artik10+python.md
- shared/getting-started/exampleProjects/raspberry-pi2+nodejs.md
- shared/getting-started/exampleProjects/raspberry-pi2+python.md
- shared/getting-started/exampleProjects/raspberrypi3+nodejs.md
- shared/getting-started/exampleProjects/raspberrypi3+python.md
- shared/network/1.x.md
> meta: Updating githubProjects repo to githubLabs

- package-lock.json
- package.json
- pages/faq/troubleshooting/faq.md
- pages/faq/troubleshooting/troubleshooting.md
- pages/learn/deploy/delta.md
- pages/learn/deploy/deployment.md
- pages/learn/develop/hardware/i2c-and-spi.md
- pages/learn/develop/integrations/aws.md
- pages/learn/develop/runtime.md
- pages/learn/manage/actions.md
- pages/learn/more/collected-data.md
- pages/learn/more/examples/projects.md
- pages/reference/OS/updates/migrate-to-2.0.md
- shared/getting-started/exampleProjects/generic/rpi-nodejs.md
- shared/getting-started/getDeviceOnDash/artik10.md
- shared/getting-started/getDeviceOnDash/artik530.md
- shared/getting-started/getDeviceOnDash/artik533s.md
- shared/getting-started/getDeviceOnDash/artik710.md
- shared/getting-started/getDeviceOnDash/kitra710.md
- shared/getting-started/getDeviceOnDash/raspberry-pi.md
- shared/getting-started/getDeviceOnDash/raspberry-pi2.md
- shared/getting-started/getDeviceOnDash/raspberrypi3.md
- shared/getting-started/getDeviceOnDash/raspberrypi4.md
- shared/network/1.x.md
- shared/network/2.x.md
- shared/overview/1.x.md
- shared/overview/2.x.md
- shared/resinSync/_default.md
- tools/test-spelling.sh
tests: add test-spelling.sh
Closes: https://github.com/balena-io/docs/issues/1300
> fix up all British spellings

- pages/learn/welcome/production-plan.md
> docs: Adding recommendation for SanDisk Extreme Pro cards

- pages/learn/develop/runtime.md
Connects-to: #1271
Signed-off-by: dt-rush <nickp@balena.io>
> wording patch to dbus hostname change warning

- pages/reference/base-images/base-images-ref.md
- pages/reference/base-images/base-images.md
Implements updates from https://github.com/balena-io/contracts/pull/142
> baseImages: Update for Debian Bullseye

- config/names.coffee
- pages/learn/deploy/release-strategy/release-policy.md
- pages/learn/more/examples/seed-projects.md
- pages/learn/more/masterclass.md
- pages/reference/OS/configuration.md
- shared/general/container-ssh.md
- shared/getting-started/balenaCliAuth/_default.md
Adding link to debugging masterclass and cleaning some formatting
> masterclass: Including link to debugging masterclass

- pages/faq/troubleshooting/faq.md
> meta: Typo fix

- shared/general/host-ssh.md
> masterclass: Add link to debugging masterclass

- config/links.coffee
> meta: Fix broken livepush link

- pages/learn/develop/container-contracts.md
> container-contracts: Fix YAML syntax in example

- pages/reference/base-images/base-images.md
Reference: https://github.com/balena-io/contracts/pull/146
> base-images: Bumping node lang versions

- config/navigation.txt
- pages/learn/more/anti-patterns.md
- pages/learn/welcome/production-plan.md
> outline development anti-patterns

- config/redirects.txt
> redirect: Add redirect for Masterclass overview

- pages/reference/supervisor/docker-compose.md
This PR was motivated by CLI issue balena-io/balena-cli/issues/1618 _(Cannot find custom dockerfile with compose files)_
Connects-to: balena-io/balena-cli/issues/1618
> Update "docker-compose.yml fields" re 'build' (path requirements)

- shared/general/labels.md
Depends on https://github.com/balena-io/balena-supervisor/pull/1205
> labels: Adding in support for sysfs and procfs

- pages/learn/develop/dockerfile.md
Discussion here: https://www.flowdock.com/app/rulemotion/i-docs/threads/8pTl055uXOBPS0Sk9ZR7mqV_qYV
> dockerfile: Adding BALENA_SERVICE_NAME variable

- pages/reference/base-images/base-images.md
Ref: https://github.com/balena-io/contracts/pull/148
> baseimage: Updates to base image contracts

- pages/learn/manage/account.md
- shared/apiGeneral/introduction.md
> warnings: stick to consistent syntax

- pages/learn/deploy/build-optimization.md
- pages/learn/develop/dockerfile.md
- pages/learn/develop/multicontainer.md
> masterclasses: Adding links to services masterclass

- pages/reference/OS/extended-support-release.md
Clarifying text based on the internal discussion here: https://www.flowdock.com/app/rulemotion/resin-propaganda/threads/QMeZEIM_-83p-2pe3x2xvyRrCJ_
> Update ESR text to clarify only two updates between ESR versions

- .gitignore
> meta: Updating gitignore to correctly ignore masterclasses

- templates/_devices.html
Related to https://github.com/balena-io/balena/issues/2122 updating to add the community label.
> devices: Adding community label to community supported boards

- pages/learn/develop/integrations/aws.md
- pages/learn/develop/integrations/bluemix.md
> Update AWS and Bluemix example repo links

- pages/learn/develop/runtime.md
> DBUS_SYSTEM_BUS_ADDRESS can be set in docker-compose.yml

- shared/general/container-ssh.md
> Adding Charlie's tip to pipe commands to CLI stdin

- pages/learn/develop/runtime.md
> Fixing broken link to OS masterclass

- pages/reference/base-images/base-images-ref.md
- pages/reference/base-images/base-images.md
Ref: https://github.com/balena-io/contracts/pull/151
Ref: https://github.com/balena-io/contracts/pull/152
> Updating base images for contract updates

- .gitignore
- config/index.coffee
- config/links.coffee
- pages/learn/more/masterclasses/overview.md
- tools/fetch-external.sh
> masterclass: Adding Docker masterclass

- .gitignore
- config/index.coffee
- config/links.coffee
- pages/learn/develop/integrations.md
- tools/fetch-external.sh
> integrations: Adding external Azure IoT Hub

- pages/learn/manage/actions.md
> Add deactivate device action

- shared/getting-started/getDeviceOnDash/intel-edison.md
> Fix broken link to Intel flash tool

- shared/deployment/secrets/_default.md
flowdock discussion: https://www.flowdock.com/app/rulemotion/i-cli/threads/MfZnNVs4gmIRqJ4AVP0dVWNlhrn
Signed-off-by: Odysseas Lamtzidis odysseas@balena.io
> Note that files in /run/secrets/ can only be copied using RUN cp

- pages/faq/troubleshooting/faq.md
- shared/general/country-firewall.md
- shared/network/2.x.md
Closes #1415 
Added some general text about accessing the VPN behind country-level firewalls and also a specific FAQ with reference to China. What else should be in here cc @alisondavis17 
> Adding note about accessing the VPN behind country level firewalls

- shared/network/2.x.md
> Clarification on network requirements for NTP/DNS

- .gitignore
- shared/meta-balena/.gitignore
- shared/sdk/.gitignore
Not sure what went on here originally other than missing the period in front of `.gitignore` but tidying this up.
> Updating .gitignore to correctly ignore external files

- config/dictionaries/resource.json
This updates `resources.json` to have the correct endpoint for the `whoami` call, and the correct fields for the response.
Test (using [httpie](https://httpie.org/)) showing the old, incorrect call:
```bash
$ http https://api.balena-cloud.com/whoami 'Authorization:Bearer [redacted]' Content-type:application/json
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, Authorization, Application-Record-Count, MaxDataServiceVersion, X-Requested-With, X-Balena-Client
Access-Control-Allow-Methods: GET, PUT, POST, PATCH, DELETE, OPTIONS, HEAD
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Connection: keep-alive
Content-Length: 12
Content-Type: text/plain; charset=utf-8
Date: Fri, 01 May 2020 17:43:06 GMT
ETag: …
```
> Correct documentation for whoami API endpoint

- pages/reference/base-images/base-images.md
Ref: /balena-io/contracts/pull/161
> Base Images stack updates

- pages/reference/OS/updates/update-process.md
Connects-to: https://github.com/balena-io/docs/pull/1407
> hostOS updates: describe delta process

- config/links.coffee
> links: add github examples repo

- pages/reference/OS/updates/self-service.md
> self-service updates: small fixups to better represent current state

- pages/learn/develop/integrations/aws.md
- static/scripts/main.js
Signed-off-by: Rahul Thakoor <rahul@balena.io>
> Fix click to deploy button in AWS IoT Integration Python mqtt example

- pages/reference/OS/updates/self-service.md
- pages/reference/OS/updates/update-process.md
Connects-to: https://github.com/balena-os/balenahup/issues/266
Depends-on: https://github.com/balena-os/balenahup/pull/267
> HUP: rename to balenahup

- pages/learn/deploy/deploy-with-balena-button.md
> deploy-with-balena: note that submodules are not currently supported

- pages/reference/base-images/base-images.md
Use the instruction for debian buster instead of jessie
> Update base images initsystem instruction (systemd)

- config/navigation.txt
> Add Docker Masterclass to LHS Navigation

- pages/reference/OS/time.md
> fix up small typo in time mgmt doc

- pages/learn/deploy/deployment.md
> Add more information to --nocache command

- config/dictionaries/device.json
- pages/reference/base-images/base-images-ref.md
- shared/general/deviceTypeNames.md
- shared/getting-started/whatYouNeed/coral-dev.md
> Update Coral Dev board name

- shared/general/deviceTypeNames.md
I didn't sort the list after renaming Coral - this fixes that
> Sort device list, correct Fin name

- config/names.coffee
- pages/faq/troubleshooting/faq.md
- pages/faq/troubleshooting/troubleshooting.md
- shared/network/1.x.md
- shared/network/2.x.md
- templates/_track.html
Page views tracking is now done with the analytics-client module.
The change also renames dashboard_domain variable to cloud_domain since the value is not really the dashboard address.
> Remove mixpanel code

- pages/faq/troubleshooting/faq.md
Applications with compatible architectures device types are also
supported, so update the FAQ accordingly.
Signed-off-by: Alex Gonzalez <alexg@balena.io>
> faq: Update mixed device types application

- config/dictionaries/resource.json
Added 
- mac_address
- api_heartbeat_state
Removed
- owns__device_log
> Update device resource API fields

- pages/learn/more/collected-data.md
- shared/network/1.x.md
Signed-off-by: Fırat Gelbal firat@balena.io
> Update data collection references to Amplitude

- pages/learn/deploy/deploy-with-balena-button.md
> Add the defaultDeviceType parameter for DWB

- pages/learn/deploy/deploy-with-balena-button.md
See: https://github.com/balena-io/balena-ui/issues/4035
> Recommend always passing a `repoUrl` query parameter

- shared/general/labels.md
> Clarify version column in Docker labels table; add balenaOS versions

- pages/learn/deploy/release-strategy/update-strategies.md
> update-strategies: fix up number + supervisor reference

- config/dictionaries/resource.json
- templates/api.html
Solves #1485 
Some previews for you all, 
@dt-rush @pdcastro @alisondavis17 :eyes:
> Document API properties 

- shared/general/labels.md
* specify location of socket inside the container
> Updates io.balena.features.balena-socket label

- shared/general/labels.md
Signed-off-by: Thomas Manning <thomasm@balena.io>
> Add `io.balena.features.journal-logs` to labels docs

- pages/learn/develop/hardware/i2c-and-spi.md
> i2c: fix up minor typos

- pages/reference/base-images/base-images.md
Update OS and stacks version to match with latest versions in contracts
> Update base images stack versions

- pages/learn/deploy/deploy-with-balena-button.md
> Add balena.yml v2 documentation

- pages/learn/deploy/deploy-with-balena-button.md
Update logo to new svg
Signed-off-by: Aaron Shaw <shawaj@gmail.com>
> Update logo to svg

- pages/learn/manage/organizations.md
> Patch Organization markdown links

- pages/learn/manage/actions.md
With organizations released, instructions were needed to be updated in accordance with the terms used and new rules applied.
Reference: https://www.flowdock.com/app/rulemotion/s-sales/threads/jEaIKEFwC1JiIHC_4rQymv463CU
> Update Transfer Ownership instructions

- pages/learn/manage/actions.md
> Remove transfer ownership video link

- pages/learn/manage/organizations.md
@notnamed :eyes: 
Resolves: #1551 
> Clarify administrator billing access

- pages/learn/more/examples/projects.md
component: Added link to Balena ADS-B Multi-Service Flight Tracker project. Corrected http to https in URL.
Signed-off-by: Ketil Moland Olsen <ketil+balenacommit@ketilmo.com>
> Added link to Balena ADS-B Multi-Service Flight Tracker project

- pages/reference/supervisor/bandwidth-reduction.md
Added column to Data Usage table to clarify which variable are associated with each data use. 
Signed-off-by:
> docs: Update 'Reduce bandwidth usage' page with clarifications

- pages/learn/deploy/deploy-with-balena-button.md
Depends-on: https://github.com/balena-io/balenahub/pull/56
Depends-on: https://github.com/balena-io/balenahub/pull/55
Depends-on: https://github.com/balena-io/balena-ui/pull/4528
Depends-on: https://github.com/balena-io/balena-builder/pull/839
Once all the dependent PRs are merged and deployed to production, we can go ahead and update all `balena.yml` files that exist out there to this new, updated schema
> Update the specification of balena.yml used for DWB

- templates/_track.html
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzothunder.ambrosi@gmail.com>
> Anonymize GoSquared IP collection

- shared/getting-started/deployingCode/nodejs.md
Signed-off-by: Stathis Moraitidis stathis@balena.io
> Add a link to the TypeScript node project

- pages/learn/develop/runtime.md
clean up some stylizations of 3ps
Connects-to: https://github.com/balena-io/balena-supervisor/pull/1469
> runtime: drop references to SUPERVISOR_VERSION env var

- config/dictionaries/resource.json
- shared/apiGeneral/versioning.md
Updated all fields directly from the API, with minor corrections to formatting as needed. 
Also resolves: #1570  #1565  
> Patch v6 fields, ID and examples

- config/dictionaries/resource.json
> Add PATCH and DELETE examples to the API documentation of device tags

- shared/getting-started/introduction/_default.md
- shared/getting-started/introduction/coral-dev+python.md
- shared/getting-started/introduction/coral-dev.md
- shared/getting-started/introduction/intel-nuc.md
> Patch 404 Host OS links in Getting Started

- config/index.coffee
- config/links.coffee
- tools/fetch-external.sh
> Fix markdown file to edit for Supervisor upgrades

- pages/reference/base-images/base-images.md
https://github.com/balena-io/balena-cli/pull/2159#discussion_r590847641
> Replace dockerfile.templates with backticked dockerfile.template

- static/css/main.css
> Improve spacing of lists

- pages/learn/manage/billing.md
Added paragraph to clarify the billing differences between inactive and offline devices
Issue #845: https://github.com/balena-io/docs/issues/845
Signed-off-by: Lizzie Epton <lizzie@balena.io>
> #845 Clarifying Inactive Vs Offline Devices

- pages/learn/develop/multicontainer.md
> add information about restart policies

- pages/learn/deploy/build-optimization.md
Fixes: #1617 
- Add multi-stage builds
- Mention image variants
- Document scratch base image
- Mention install_packages utility
Signed-off-by: Rahul Thakoor <rahul@balena.io>
> Improve build optimization instructions

- tools/fetch-external.sh
> Parallelize external docs fetching, dropping from 8s to 3s locally

- config/links.coffee
> Fix broken link for contributing to CLI docs

- pages/learn/welcome/introduction.md
component: removed typo
Fixes #1692 
Signed-off-by: Laura Alison <laura@poshrolls.co.uk>
> Removed typo

- package-lock.json
- package.json
> Update doxx to bring in performance improvements

- pages/learn/deploy/build-optimization.md
Signed-off-by: Rahul Thakoor <rahul@balena.io>
> Fix $names.company to $names.company.upper

- pages/learn/manage/app-types.md
Signed-off-by: Alison Davis Riddell alison@balena.io
> Changing app types when upgrading plan

- pages/learn/deploy/delta.md
Closes: #1542
Signed-off-by: Tomás Migone <tomas@balena.io>
> deltas: fix links on deltas page

- pages/learn/manage/app-types.md
Resolves #1460
Signed-off-by: Micah Halter <micah@balena.io>
> Added note that inactive devices count against starter application limit

- pages/reference/hardware/wifi-dongles.md
Signed-off-by: jasmine <jasmine@balena.io>
> Update beaglebone green link

- pages/learn/develop/runtime.md
Signed-off-by: Andrew N. <andrew@balena.io>
> Fix balena_restart_device typo

- pages/learn/manage/account.md
> Password for social login

- pages/learn/manage/serv-vars.md
> Document maximum env/service/app variable value size

- shared/getting-started/whatYouNeed/asus-tinker-board-s.md
- shared/getting-started/whatYouNeed/asus-tinker-board.md
> Correct supported devices list links fixes #1682

- pages/learn/manage/actions.md
@apostolism @thgreasi :eyes: 
In reference to: [FD thread](https://www.flowdock.com/app/rulemotion/resin-frontend/threads/NgCdlUJ2WYwNZKC0ke7h7WUutSc)
> Clarify type of application required for transferring ownership

- pages/learn/more/examples/snippets.md
Signed-off-by: jasmine <jasmine@balena.io>
> Fixed broken project link for nodejs picamera

- pages/learn/welcome/primer.md
When I read this, I expect it to take me to a definition of a Build Server, which I think this specific link does better than the generic /deployment page.
> Suggest pointing to specific section

- package-lock.json
- package.json
- repo.yml
- server/index.coffee
- tools/test-nav.coffee
Update @balena/doxx from 0.11.5 to 1.0.0
> Update/switch to @balena/doxx, picking up a lot of nested changes

- README.md
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>
> Change use of "resin" to "balena" in README

- pages/faq/troubleshooting/faq.md
Signed-off-by: Rafael Morillo <rafael@balena.io>
> Adding genericX86_64 to the device types to try

- pages/learn/manage/account.md
Signed-off-by: Ryan Cooke <ryan@balena.io>
> add matrix to the member types

- pages/learn/manage/serv-vars.md
> Clarify section about device env vars and bandwidth usage

- tools/fetch-external.sh
> Simplify and further parallelize fetching external docs

- shared/network/2.x.md
Links to: https://github.com/balena-io/docs/issues/1771
Signed-off-by: Joseph Kogut <joseph@balena.io>
> networking: fix py2/3 compatibility in dbus example

- pages/reference/supervisor/supervisor-upgrades.md
> Move Supervisor upgrade policy to self-serve document

- pages/learn/develop/local-mode.md
Signed-off-by: Michael Wilks <michael@balena.io
> Edits to correct typos

- pages/learn/deploy/deploy-with-balena-button.md
- pages/reference/OS/updates/migrate-to-2.0.md
- pages/reference/hardware/wifi-dongles.md
- shared/getting-started/whatYouNeed/bananapi-m1-plus.md
- shared/getting-started/whatYouNeed/fincm3.md
- shared/getting-started/whatYouNeed/odroid-c1.md
- shared/getting-started/whatYouNeed/odroid-xu4.md
- shared/network/2.x.md
Relates to #1621
Extracted from https://github.com/balena-io/docs/pull/1658
> Update a number of broken links

- pages/reference/OS/meta-balena.md
Signed-off-by: Florin Sarbu <florin@balena.io>
> OS:meta-balena.md: Update device contribution guide

- shared/getting-started/getDeviceOnDash/intel-nuc.md
Minor update for my NUC model.
Starting simply -- my first doc commit as a balenista.
> Extend Intel NUC Getting Started for power button location

- pages/learn/getting-started.md
Fixes #1732
Signed-off-by: Somo Sakala <somo@balena.io>
> Add balenaHub link to end of getting started guide

- pages/learn/deploy/deployment.md
- pages/learn/more/masterclasses/overview.md
- shared/deployment/secrets/_default.md
Signed-off-by: alexandra <alexandra@balena.io>
> Fix Typos on multiple pages

- pages/faq/troubleshooting/troubleshooting.md
Signed-off-by: Josh Bowling <josh@balena.io>
> Fix grammar issues in troubleshooting doc

- LICENSE
Well.. this is awkward. Glad we have it now ✔️
> patch: Add LICENSE

- pages/learn/manage/organizations.md
> patch: update text in Creating teams

- pages/learn/deploy/offline-updates.md
> Patch: Correct typo in offline updates

- pages/learn/manage/actions.md
Signed-off-by: Joe Hounsham <joeh@balena.io>
*Please check the [CONTRIBUTING.md](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) 
file for relevant information on contributing to the documentation.*
Thank you very much for your contribution!
> Updating actions page ( Application Ownership Transfer) 

- pages/learn/manage/device-statuses.md
*Please check the [CONTRIBUTING.md](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) 
file for relevant information on contributing to the documentation.*
Thank you very much for your contribution!
> device-status: add missing period

- pages/learn/manage/account.md
Also reorders app member types table to be descending by access level like the UI.
Resolves: #1839
*Please check the [CONTRIBUTING.md](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) 
file for relevant information on contributing to the documentation.*
Thank you very much for your contribution!
> account: Fix Developer & Operator access to devices

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Adding further changes to CG from feedback received.
> Improve Contributing Guide

- pages/reference/OS/updates/update-process.md
This is a PR to add some extra info about the automatic rollback to our docs
> Improve the automatic rollback documentation on our docs

- pages/learn/manage/billing.md
Connects to https://github.com/balena-io/docs/issues/1788
Signed-off-by: Fırat Gelbal firat@balena.io
> Explain the most feature rich dynamic billing

- templates/_track.html
Also added Navigation Click tracking for links to githubMain URL
such as Improve this Doc button.
Change-type: Minor
Signed-off-by: Ezequiel Boehler ezequiel@balena.io
*Please check the [CONTRIBUTING.md](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) 
file for relevant information on contributing to the documentation.*
Thank you very much for your contribution!
> Updated analytics-client version

- pages/learn/develop/runtime.md
Connects to https://github.com/balena-io/docs/issues/591
Signed-off-by: Fırat Gelbal firat@balena.io
> Add warning on DBUS command usage

- CONTRIBUTING.md
Folks were missing out on reading the style guide when making
pull requests so added a reference for it in the CONTRIBUTING document.
---
> patch: add best practices section to contributing

- shared/getting-started/getDeviceOnDash/beaglebone-black.md
- shared/getting-started/getDeviceOnDash/beaglebone-green.md
- shared/getting-started/getDeviceOnDash/coral-dev.md
- shared/getting-started/getDeviceOnDash/raspberry-pi.md
- shared/getting-started/getDeviceOnDash/raspberry-pi2.md
- shared/getting-started/getDeviceOnDash/raspberrypi3-64.md
- shared/getting-started/getDeviceOnDash/raspberrypi3.md
- shared/getting-started/getDeviceOnDash/raspberrypi4-64.md
- shared/getting-started/getDeviceOnDash/ts4900.md
Issue: https://github.com/balena-io/docs/issues/478
> Updating the HDMI output note to reflect output starting v2.0 on Raspi devices

- shared/network/2.x.md
> Addition: how to set address used for shared interface

- pages/faq/troubleshooting/faq.md
The networking and NTP server questions repeated the information that already exists at other places in our documentation. Moreover, the information in this text was not accurate/up-do-date. Hence, replaced the text with appropriate links.
> Patch: Updated answers to networking & NTP questions.

- pages/learn/manage/account.md
Signed-off-by: Thomas Manning <thomasm@balena.io>
Fixes #1878
> patch: Fix administrator link on manage account page

- pages/faq/troubleshooting/faq.md
Changed 'Network Ports' to 'network ports' in the ToC.
Signed-off-by: Pranav Peshwe <pranav@balena.io>
> Patch: Minor grammatical fix in the ToC.

- pages/learn/deploy/release-strategy/update-strategies.md
cross-referencing features influencing the update process
> reference application update locks from update strategy docs

- pages/reference/base-images/legacy-base-images.md
> Fixed broken link and typo

- pages/learn/develop/dockerfile.md
Fix typo the anchor part of the link.
> Fix link to CLI build command

- pages/learn/develop/hardware.md
- pages/learn/develop/hardware/usb.md
> Add interfacing with USB devices to hardware docs

- pages/learn/manage/actions.md
Connects-to: balena-os/balena-supervisor#1708
Signed-off-by: Christina Wang <christina@balena.io>
---
> Clarify that restart will remove and recreate containers

- pages/learn/deploy/offline-updates.md
- pages/reference/OS/meta-balena.md
- shared/general/host-ssh.md
> docs: Rename resin-supervisor to balena-supervisor

- .github/CODEOWNERS
> patch: update CODEOWNERS

- pages/faq/troubleshooting/faq.md
Added `Does balena have access to my device, source code and images?` question
---
> minor: added device access FAQ

- shared/general/host-ssh.md
- shared/getting-started/usingSupport/_default.md
Signed-off-by: Stathis Moraitidis <stathis@balena.io>
> Fix broken forum links on using support and troubleshooting host OS

- .github/CODEOWNERS
> Added docs team to CODEOWNERS

- templates/devices.html
WIP - Will add a note to this page as well https://www.balena.io/docs/reference/base-images/devicetypes/ when #1915 is merged
---
> patch: Add link to refer to CDS

- pages/reference/base-images/devicetypes.md
- templates/_machines-architectures.html
- templates/default.html
- templates/machines-architectures.html
Connects-to: #1902 
Dynamically generate content from api v6/device_type endpoint
---
> Update base images device types page

- pages/learn/welcome/security.md
Before googleing for this topic and Balena didn't yield useful results
> add note about responsible disclosure

- pages/learn/deploy/release-strategy/update-strategies.md
- pages/learn/develop/local-mode.md
- pages/learn/manage/configuration.md
- pages/reference/OS/advanced.md
- shared/general/config-variables-pi.md
Resolves: https://github.com/balena-io/docs/issues/1858
---
> Rename RESIN_ environment variable references

- pages/learn/manage/actions.md
Updating the actions page to reflect the recent role changes that grant additional functionality and/or expose existing functionality in the UI and API to Operator and Developer users.
Signed-off-by: Jordan Cooks jordan@balena.io
> Specify which user roles can perform which actions

- pages/learn/develop/runtime.md
Signed-off-by: Joseph Kogut <joseph.kogut@gmail.com>
---
> runtime: add example for stopping host OS service

- Dockerfile
See: https://docs.google.com/spreadsheets/d/1nyvLWrFnZQCelKhdyR9XlFIQnRtXdVXKvmb7qoAjrww/edit#gid=0
---
> Bump node 14.17.1 to fix debian dependency security issues

- pages/learn/manage/configuration.md
See: https://jel.ly.fish/32cc2ee4-c5a7-4ec8-8e91-1ba4f1379bc4
See: https://www.flowdock.com/app/rulemotion/r-product/threads/9mk8QcdNp4UAwKeEUpXPHVxYM_c
---
> Add the OVERRIDE_LOCK config var to the variables list

- .github/dependabot.yml
> Enable dependabot for docker

- .github/workflows/link-checker.yml
- pages/learn/develop/runtime.md
> Fix bind9 URL and omit some URLs in link-checker

- pages/learn/manage/actions.md
See: https://www.flowdock.com/app/rulemotion/r-product/threads/b0S9epziNSpbShwcrTI4zG3-Dwq
Signed-off-by: Christina Wang <christina@balena.io>
> Explain why balena's restart action is different than Docker restart

- pages/learn/manage/account.md
See: https://github.com/balena-io/balena-api/pull/3232
HQ: https://jel.ly.fish/e450713f-001c-4470-b571-71724aeb0869
---
> Document that Operators can manage provisioning API keys

- Dockerfile
See: https://docs.google.com/spreadsheets/d/1nyvLWrFnZQCelKhdyR9XlFIQnRtXdVXKvmb7qoAjrww/edit#gid=151739310
---
> Bump node 14.17.2 to fix debian dependency security issues

- templates/_track.html
Signed-off-by: Fırat Gelbal firat@balena.io
> Sunset GoSquared

- pages/learn/develop/hardware/gpio.md
reference: https://github.com/balena-io/docs/issues/1989
Change-type:patch
---
> Removed broken GPIO library reference

- pages/reference/OS/configuration.md
- pages/reference/OS/updates/migrate-to-2.0.md
- shared/network/2.x.md
Resolves: https://github.com/balena-io/docs/issues/1996
> Update links to network manager documentation

- pages/learn/getting-started.md
- shared/getting-started/flashingOsToBootMedia/_default.md
- shared/getting-started/getDeviceOnDash/fincm3.md
- shared/getting-started/getDeviceOnDash/generic-aarch64.md
- shared/getting-started/getDeviceOnDash/revpi-core-3.md
- shared/getting-started/introduction/_default.md
- shared/getting-started/introduction/coral-dev+python.md
- shared/getting-started/introduction/coral-dev.md
- shared/getting-started/introduction/intel-nuc.md
- shared/getting-started/projectSpecific/_default.md
- shared/getting-started/projectSpecific/coral-dev+python.md
> Update fleets in Getting started guides

- pages/learn/develop/local-mode.md
Needs additional check to ensure context is correct. 
Signed-off-by: Laura Alison <@poshrolls>
---
> Local-mode: Renaming to app from application

- pages/learn/manage/support-access.md
Renames application to fleet
Screenshots not updated
> patch: Rename application to fleet

- pages/learn/more/anti-patterns.md
- pages/learn/more/collected-data.md
- pages/learn/more/examples/balenablocks.md
> Replace application with fleets for More Resources section

- pages/faq/troubleshooting/faq.md
- pages/faq/troubleshooting/troubleshooting.md
> Change application to fleets for FAQ section

- pages/learn/more/masterclasses/overview.md
Signed-off-by: Matthew Yarmolinsky <matthew-timothy@balena.io>
---
> Update Fleets in Masterclass Overview

- pages/learn/manage/account.md
change-type: patch
signed-of-by: Laura Alison <@poshrolls>
---
> Update account.md rename fleets / apps

- pages/learn/manage/organizations.md
change-type: patch
signed-off-by: Laura Alison <laura@balena.io>
---
> update org pages

- pages/learn/manage/app-types.md
change-type: patch 
signed-off-by: Laura Alison <@poshrolls>
---
> Text updates  - app types - applications to fleets

- pages/learn/manage/filters-tags.md
Update to change references of Applications to Fleets
---
> patch: Update filters-tags.md

- pages/learn/manage/device-statuses.md
Update to change references of Applications to Fleets
---
> patch: Update device-statuses.md

- pages/learn/manage/serv-vars.md
Update to change references of 'application' to 'fleet'
---
> patch: Update serv-vars.md

- pages/learn/manage/configuration.md
Updated application to fleet. Screenshots may still be not covering the renaming and will be updated later.
> patch: rename application to fleet in

- pages/learn/develop/container-contracts.md
- pages/learn/develop/dockerfile.md
- pages/learn/develop/hardware.md
- pages/learn/develop/hardware/i2c-and-spi.md
- pages/learn/develop/multicontainer.md
- pages/learn/develop/runtime.md
> Update fleets/app in develop section

- config/dictionaries/resource.json
- templates/api.html
> Update API resources with fleets rename

- pages/reference/supervisor/device-metrics.md
Resolves: https://github.com/balena-io/docs/issues/2046
> Updating missing image caused by blog migration

- shared/general/container-ssh.md
Connects-to: balena-io/balena-cli/issues/2292
See: https://www.flowdock.com/app/rulemotion/public-s-community/threads/CRkdpV1bqqbcu3QLZnZnoDGQ8Nw
> SSH access docs: clarify authentication with balenaCloud username

- config/redirects.txt
- shared/apiGeneral/introduction.md
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>
> Fix API resources link and API reference redirects.

- shared/getting-started/cliInstructions/_default.md
Link id was misnamed, causing jquery to fail to show the tab on load
> Fix linux cli install tab

- pages/faq/troubleshooting/troubleshooting.md
> troubleshooting: Add more Jetson frequently asked questions

- pages/reference/base-images/base-images.md
> Update latest base images versions

- pages/learn/manage/account.md
- pages/learn/manage/actions.md
Hey @balena-io/docs do take a look as we might need to add new columns to this member access table, especially `settings` and renaming some columns as well. We don't have docs for fleet actions AFAIK. 
﻿Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>
---
> Add links to member table

- pages/learn/develop/hardware/i2c-and-spi.md
- pages/learn/manage/configuration.md
- pages/reference/OS/advanced.md
- shared/getting-started/getDeviceOnDash/fincm3.md
- shared/getting-started/getDeviceOnDash/revpi-core-3.md
> patch: Fix redirected Raspberrypi links

- .github/dependabot.yml
- .github/workflows/link-checker.yml
> Update Link Checker action

- .github/workflows/link-checker.yml
> patch: Fix link checker name syntax

- shared/deployment/secrets/_default.md
Fix inline code.
Fix wrong command, there is no mention of `secret-recipe` before it is used.
> patch: fix minor errors

- .github/workflows/link-checker.yml
> patch: Put quotes on lychee glob path

- config/navigation.txt
> patch: Add USB page to navigation

- config/redirects.txt
- pages/faq/troubleshooting/troubleshooting.md
> patch: Fix masterclass redirect logic

- pages/learn/manage/account.md
> patch: Fix link for fleet actions in member table

- config/redirects.txt
Signed-off-by: Nitish Agarwal <1592163+nitishagar@users.noreply.github.com>
See: https://www.flowdock.com/app/rulemotion/i-docs/threads/rY_MPcMMhCEd6Z9OHiJyI8wdXIg
> Fix redirect from /data-api to /reference/api

- pages/learn/welcome/security.md
Updated Packet.com to metal.equinix.com
> Updated Packet.com to metal.equinix.com

- shared/general/container-ssh.md
Connects-to: balena-io/balena-cli/pull/2457
Connects-to: balena-io/balena-cli/pull/2461
> Update SSH access docs ('balena ssh' usage with production OS variants)

- pages/learn/welcome/security.md
Add explanation around how the VPN disallows device-to-device traffic
---
> Update info re. VPN

- pages/learn/develop/blocks.md
> patch: Replace blocks image with registry URL

- pages/faq/troubleshooting/troubleshooting.md
- pages/learn/develop/hardware/i2c-and-spi.md
> pages: Add details for custom device-tree support on Jetson Devices

- shared/network/2.x.md
> Fixed cellular link

- shared/network/2.x.md
resin-sample -> balena sample
---
> resin-sample -> balena sample

- shared/network/2.x.md
Fixed intra doc link for updating usb current
---
> Fixed intra doc link for updating usb current

- pages/learn/deploy/release-strategy/update-strategies.md
> Modify update strategies to reference labels

- shared/getting-started/getDeviceOnDash/fincm3.md
Signed-off-by: Alex Bucknall <alex.bucknall@gmail.com>
---
> Removes reference to missing balenaFin images.

- config/dictionaries/resource.json
Update-tag requires the tag filter in the URL instead of in the data
---
> Patch: Correct update-tag syntax

- .github/workflows/link-checker.yml
Let me know what you feel about this one @klutchell, I think this might be helpful in bringing down our invalid URL's
---
> patch: Check links in generated HTML instead

- .github/workflows/deploy-to-heroku.yml
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>
---
> Fixup typo in GH deployment action.

- pages/learn/deploy/deploy-with-balena-button.md
Context: https://jel.ly.fish/support-thread-discourse-357896
---
> patch: Add blocks docs reference in DWB

- config/redirects.txt
> Expand redirect regex to cover more URLS

- .github/workflows/link-checker.yml
- lychee.toml
The link checker wasn't working correctly for HTML files so dove deep in Lychee and resolved the issues
---
> patch: Resolve link checker issues for HTML files

- pages/learn/develop/multicontainer.md
- pages/reference/supervisor/docker-compose.md
> Specify default container restart policy.

- shared/getting-started/cliInstructions/_default.md
Signed-off-by: Flynn Joffray <flynn@balena.io>
Fixes https://github.com/balena-io/docs/issues/2297
> patch: adding fix for getting-started cli tab list

- pages/learn/develop/multicontainer.md
See: https://github.com/balena-io/docs/pull/2302
---
> Update the restart policy link to point to the docker-compose v2 docs

- .gitignore
- config/index.coffee
- config/links.coffee
- config/navigation.txt
- config/redirects.txt
- tools/fetch-external.sh
CBS is actually Customer Board Support, hence making the change.
FD: https://www.flowdock.com/app/rulemotion/i-docs/threads/Ab3qdFisLJYSiktJq22XUyNJdyT
---
> patch: Replace CBS to Customer Board Support

- lychee.toml
Trying to optimize our Lychee runs further with suggestions from https://github.com/lycheeverse/lychee/issues/634
---
> patch: Reduce false positives by accepting 429 in lychee

- server/index.coffee
> patch: Provide server URL with correct path

- pages/learn/welcome/support.md
- shared/getting-started/usingSupport/_default.md
> patch: Deprecate support partial

- .github/workflows/link-checker.yml
- .gitignore
- lychee.toml
> patch: Update lychee to 1.5.0

- config/index.coffee
- config/links.coffee
- config/redirects.txt
- pages/learn/manage/apps.md
- pages/reference/api/resources.md
Signed-off-by: Nitish Agarwal <1592163+nitishagar@users.noreply.github.com>
See: https://www.flowdock.com/app/rulemotion/i-docs/threads/GhWvQLvvFafs1vRPlyB6YvAL_TS
> Add redirect from /application to /fleet to fix 404 link

- pages/learn/manage/actions.md
Includes more information that customers ask about a pending transfer
---
> Updated the Fleet Xfer Docs

- pages/learn/manage/actions.md
Reverts balena-io/docs#2352 with the comment https://github.com/balena-io/docs/pull/2352#issuecomment-1197253421
> Revert "Updated the Fleet Xfer Docs"

- pages/learn/deploy/release-strategy/update-strategies.md
Resolves: https://github.com/balena-io/docs/issues/2351
> update-strategies: Fix link to supervisor docker-compose labels

- pages/learn/deploy/release-strategy/update-strategies.md
> Add disclaimer about delete-then-download

- .github/workflows/deploy-to-heroku.yml
> patch: Fix Healthcheck URL

- templates/_devices.html
> Exclude Device Types w/o hostApp releases from the Supported Devices

- pages/reference/base-images/base-images.md
> patch: Update latest supported OS/stack versionsf for balena base-images

- pages/reference/OS/network.md
Added details about where DNS from DHCP is coming from
---
> Add info about source of DNS in balenaOS

- pages/learn/deploy/release-strategy/update-strategies.md
Signed-off-by: Nitish Agarwal <1592163+nitishagar@users.noreply.github.com>
> Remove the embedded link from old configuration

- .github/workflows/link-checker.yml
- lychee.toml
The issue https://github.com/lycheeverse/lychee/issues/644 has been resolved. Hence, specifying the correct HTTP status codes in the config file.
---
> patch: Accept 429 HTTP codes using config file

- .versionbot/CHANGELOG.yml
> Add .versionbot/CHANGELOG.yml

- pages/reference/OS/network.md
> patch: Fix link for supported modems in network docs

- pages/learn/manage/billing.md
Modified the section Inactive vs. Offline to make it more clear how it works, when it's billed and when the billing is resumed.
---
> patch: clarifying offline vs inactive

- package-lock.json
- package.json
> Update dependencies & lockfile

- Dockerfile
> patch: Update Dockerfile to v16

- config/dictionaries/resource.json
> patch: Remove links from API docs

- templates/_track.html
Signed-off-by: Otavio Jacobi <otavio.jacobi@balena.io>
---
> Bump analytics-client to version 2

- pages/reference/base-images/base-images.md
> Update latest base images stack versions

- pages/learn/deploy/release-strategy/update-strategies.md
> Specify the default update strategy in the list of options

- static/css/main.css
- static/css/menu-top.css
- static/css/search.css
- static/scripts/main.js
- templates/_algolia.html
- templates/_search-form-mobile.html
- templates/_search-form.html
- templates/_top-menu.html
- templates/default.html
- templates/not-found.html
Upgraded docsearch to v3 
- improved views for mobile
- Made header non-sticky for a better appeal
---
> minor: Upgrade docsearch to v3

- pages/learn/develop/cloud-iot-provisioning.md
Temporary fix for #2431 until we completely remove the documentation.
> Add deprecation notice for GCP IoT provisioning

- tools/build-masterclass.sh
> Fix Networking section debugging masterclass

- config/navigation.txt
- config/redirects.txt
- pages/learn/more/glossary.md
- pages/learn/welcome/glossary.md
- pages/learn/welcome/introduction.md
- pages/learn/welcome/primer.md
- tools/build.sh
- tools/prepare.sh
Move the glossary to more resources section
---
> Update Primer with Core Concepts page

- config/redirects.txt
- tools/deploy-static.sh
Cloudflare Pages treats redirects with and without trailing slashes separately as per their documentation. So for every redirect we need to check that we have included both variations.
---
> deploy-static: Exit with error if any redirects are missing

- pages/faq/troubleshooting/troubleshooting.md
- pages/learn/develop/runtime.md
- shared/getting-started/getDeviceOnDash/beaglebone-green.md
- templates/config.html
> patch: Fix broken links

- pages/learn/manage/billing.md
> Added Device Freezing to Billing Page

- .github/workflows/link-checker.yml
- config/index.coffee
- lychee.toml
- package-lock.json
- package.json
- tools/build-masterclass.sh
> patch: Update lychee to commit v1.5.4

- pages/learn/welcome/introduction.md
> patch: Update Roadmap link

- pages/learn/manage/billing.md
> Credit calc label tweak

- .github/workflows/link-checker.yml
> patch: add good-first-issue tag to Link Checker issues

- package-lock.json
- package.json
- pages/learn/welcome/introduction.md
> Update introduction page with links

- pages/learn/manage/fleet-types.md
> Updated fleet type docs for sunset

- pages/learn/manage/fleet-types.md
> Removed upgrade section

- .github/workflows/deploy-to-cloudflare-pages.yml
> Fix errors in Cloudflare Action

- pages/faq/troubleshooting/faq.md
- pages/learn/deploy/deployment.md
- pages/learn/manage/account.md
- pages/learn/manage/actions.md
- pages/learn/manage/billing.md
- pages/learn/manage/fleet-types.md
> updates to prep for Pricing changes

- config/navigation.txt
- config/redirects.txt
- pages/faq/troubleshooting/troubleshooting.md
- shared/troubleshooting/intel-nuc.md
- shared/troubleshooting/jetson-tx2.md
- shared/troubleshooting/odyssey-x86.md
- shared/troubleshooting/raspberry-pi.md
- shared/troubleshooting/raspberry-pi2.md
- shared/troubleshooting/raspberrypi0-2w-64.md
- shared/troubleshooting/raspberrypi3-64.md
- shared/troubleshooting/raspberrypi3.md
- shared/troubleshooting/raspberrypi4-64.md
- shared/troubleshooting/raspberrypicm4-ioboard.md
- shared/troubleshooting/up-board.md
- shared/troubleshooting/var-som-mx6.md
- templates/troubleshooting.html
This implements a way for us to have device type specific troubleshooting information that can be provided to customers, referenced in blog posts and redirected to from Getting Started guides. 
Patterns for specific device types can be documented here to have the information be visible to users. 
---
> minor: Convert to device-type specific troubleshooting

- .github/workflows/deploy-to-cloudflare-pages.yml
> patch: Install latest wrangler version

- pages/learn/manage/billing.md
> Added 24 hour credit note

- pages/reference/base-images/devicetypes.md
- pages/reference/hardware/devices.md
- templates/_devices.html
- templates/_machines-architectures.html
- templates/devices.html
- templates/machines-architectures.html
With balenaHub turning a new chapter, it's time to add back these lists to docs. 
---
> minor: Add Supported Device Type list

- config/index.coffee
- config/links.coffee
- tools/build-masterclass.sh
- tools/fetch-external.sh
> patch: Fix troubleshooting edit links

- .github/workflows/link-checker.yml
> patch: Update lychee to 1.6.1

- lychee.toml
> patch: Add verbose level to lychee output

- pages/faq/troubleshooting/faq.md
> patch: Add Generic x Device Type difference

- pages/learn/manage/actions.md
Add Release Settings documentation for `Validation status` and `Delete`
---
> Add Release Settings documentation for `Validation status` and `Delete`

- .github/workflows/deploy-to-cloudflare-pages.yml
> patch: Supply Cloudflare Pages project name

- package-lock.json
- package.json
- static/robots.txt
- tools/deploy-static-page.sh
> patch: Add sitemap.xml

- static/robots.txt
> patch: Add Algolia crawler verification code

- lychee.toml
- shared/troubleshooting/jetson-nano-2gb-devkit.md
- shared/troubleshooting/jetson-nano-emmc.md
- shared/troubleshooting/jetson-nano.md
- shared/troubleshooting/jetson-tx2-nx-devkit.md
- shared/troubleshooting/jetson-tx2.md
#2570 deleted troubleshooting content related to several Jetson devices. Redding them back with this PR.    
---
> patch: Add back troubleshooting content for jetson devices

- config/navigation.txt
- pages/learn/getting-started.md
Referred to @chrisys here: https://balena.zulipchat.com/#narrow/stream/350505-aspect.2Fmarketing/topic/Full.20auto.20Getting.20Started.20.2F.20Contract.20based.20Instructions/near/342659847
---
> patch: Improve SEO ranking of Getting Started guide

- pages/learn/develop/multicontainer.md
This documents the change made in https://github.com/balena-os/meta-balena/pull/2849 .
> Document how to enable core dumps for containers

- .github/workflows/link-checker.yml
- package-lock.json
- package.json
Updated lychee to solve https://github.com/lycheeverse/lychee-action/issues/191 
---
> Update Lychee to v1.7.0 

- pages/learn/deploy/release-strategy/release-policy.md
Release policy: Fix target release pencil image not working
Resolves: #2686 
---
> Release policy: Fix target release pencil image not working

- lychee.toml
> Add info level to lychee logs

- pages/learn/deploy/offline-updates.md
> Remove unnecessary `prod` filter on balena os versions

- .cspell/computer-terms.txt
- pages/learn/develop/hardware/i2c-and-spi.md
> hardware: Add Jetson Orin NX module to list of custom dtb devices

- pages/learn/develop/hardware/i2c-and-spi.md
The existing sample application is now old, let's use the balena-sense project as an example for I2C.
---
> develop/hardware: Update I2C example in the i2c-and-spi section

- pages/faq/troubleshooting/debugging-storage-media.md
Resolves #2556 to add corruption detection command
---
> patch: Add command to check device corruption

- pages/faq/troubleshooting/faq.md
Thread: https://balena.zulipchat.com/#narrow/stream/345746-aspect.2Fproduct/topic/balenaFin.20discontinuation
Arch call: https://drive.google.com/file/d/1hl1D3q9AwpUrp7XxgQk7HoGDInWL_Z0J/view?usp=drive_web
> faq/troubleshooting: when are device types discontinued

- pages/faq/troubleshooting/faq.md
> trobleshooting/faq: update section about generic architecture images

- pages/learn/develop/hardware/i2c-and-spi.md
> develop/hardware: Add Orin Nano to the list of devices with custom dtb support

- package-lock.json
- package.json
- pages/reference/OS/overview.md
- shared/getting-started/whatYouNeed/asus-tinker-board-s.md
- shared/getting-started/whatYouNeed/asus-tinker-board.md
- shared/getting-started/whatYouNeed/fincm3.md
- shared/getting-started/whatYouNeed/jetson-xavier-nx-devkit.md
- shared/getting-started/whatYouNeed/revpi-core-3.md
- tools/build-masterclass.sh
- tools/fetch-external.sh
> Fix Docs links

- pages/learn/develop/runtime.md
> Add note that udev requires the root user

- .github/workflows/flowzone.yml
Added changes from config to allow Flowzone runs on external contributors
> patch: Allow pull requests from external contributors

- pages/reference/OS/network.md
Support for NM user scripts was introduced in balenaOS v3.1.3.
> Document NetworkManager dispatch user scripts

- pages/learn/manage/account.md
Improve instructions for members removing themselves from fleets
---
> Improve instructions for members removing themselves from fleets

- .github/workflows/deploy-to-cloudflare-pages.yml
> patch: Pin Cloudflare to latest version

- pages/faq/troubleshooting/debugging-storage-media.md
> patch: Fix formatting for debugging masterclass

- pages/learn/develop/cloud-iot-provisioning.md
> patch: Fix dead link in Cloud Provisioning docs

- config/dictionaries/resource.json
See: https://balena.fibery.io/Work/Task/Should-have-docs-about-release-versioning-draft-releases-683
> Add the release versioning fields in the resource reference

- config/redirects.txt
> patch: Fix RaspberryPi 5 redirects

- .github/workflows/deploy-to-cloudflare-pages.yml
- .github/workflows/link-checker.yml
- package-lock.json
- package.json
- patch: Update actions/checkout to v4
- patch: Update actions/checkout to v4
- Update cloudflare/wrangler-action to v3.3.1
- Update NPM dependencies
> Update GH actions & Dependencies

- pages/learn/manage/variables.md
Adds another degree of clarification as to what happens when variables in balenaCloud change. 
---
> patch: Signify behavior when variables change

- config/dictionaries/resource.json
See: https://jel.ly.fish/support-thread-1-0-0-front-cnv-essp2od
> API/Resources: Add examples for retrieving API Keys & updating their expiry date

- pages/learn/deploy/deployment.md
> patch: Add balena build/deploy command reference

- pages/learn/deploy/deployment.md
> patch: Add GitHub container registry to registry-secrets docs

- pages/reference/OS/updates/self-service.md
> os: self-service updates: document the requirement of exclusive locks

- pages/learn/develop/hardware/i2c-and-spi.md
Connects-to: Internal thread https://balena.zulipchat.com/#narrow/stream/403752-channel.2Fsupport-help/topic/Can't.20access.20the.20serial.20port.20on.20Up.20Squared.20device/near/404364945
---
> develop/hardware: Add info on Up Squared UART communication

- pages/learn/develop/hardware/i2c-and-spi.md
> develop/hardware: Update Up Squared uart info

- pages/learn/develop/hardware/i2c-and-spi.md
> develop/hardware: Reword information on up board pin configuration

- pages/learn/develop/local-mode.md
> Update local-mode.md - correct first --system example

- .github/workflows/link-checker.yml
- lychee.toml
- pages/learn/develop/hardware/i2c-and-spi.md
- pages/learn/more/glossary.md
Fixing the links reported by Lychee 
> patch: Fix links in Glossary and base images

- pages/faq/troubleshooting/troubleshooting.md
Add Troubleshooting section for `This is the wrong balena device` error
Connects-to: https://github.com/balena-io/balena-proxy/pull/1095
---
> Add Troubleshooting section for `This is the wrong balena device` error

- .github/workflows/deploy-to-cloudflare-pages.yml
- lychee.toml
- pages/faq/troubleshooting/troubleshooting.md
- server/index.coffee
- static/css/main.css
Changes include
- Update publish step in Cloudflare Action (directly got that from changes made in Flowzone)
- Change /docs to / on docs server start (A DX change to redirect to working URLs)
- Fix dead link about LED error notifications & improve LED indicator docs
- Remove unordered list from CSS margin property
> Troubleshooting Docs: Fix dead links, docs, CSS tweaks

- .gitignore
- tools/build-masterclass.sh
- tools/fetch-external.sh
> patch: Add Diagnostics section as subpages in docs

- pages/reference/OS/advanced.md
> Clarify global dtparams: should have own set of double quotes

- pages/learn/getting-started.md
- shared/getting-started/whatYouNeed/_default.md
Minor improvements to what you need section in the Getting Started guide.
---
> patch: Improve Whatyouneed section in Getting Started

- config/index.coffee
- config/links.coffee
> patch: Fix Supervisor Configuration list

- .github/workflows/link-checker.yml
- config/navigation.txt
Additionally, creating a change for remove the `good-first-issue` label from automated link checker report issues.
---
> patch: Add Diagnostics headings to navigation sidebar

- lychee.toml
- pages/learn/develop/hardware/gpio.md
Creating since we are still getting 429 error status codes in #2947 
---
> patch: Add double quotes for accept status codes

- .github/workflows/link-checker.yml
> patch: Update lychee to v1.10

- config/dictionaries/resource.json
> API/Resources: Add docs updating the supervisor of a device

- pages/reference/base-images/base-images.md
Before we move towards automating this page completely, I am hoping this change would move the needle towards eliminating specific links to locations that go out of date quickly to links that can survive longer. 
> patch: Update Balena Base Images 404 links

- pages/reference/api/overview.md
> Change overview to point at v6 rather than v5

- .github/workflows/deploy-to-cloudflare-pages.yml
- package-lock.json
- package.json
- **patch: Update NPM dependencies**
- **Update GitHub Action dependencies**
---
> Update NPM & GH Action dependencies

- pages/learn/accounts/enterprise-sso.md
- pages/learn/accounts/idp-setup/google-workspace-saml-setup.md
- pages/learn/accounts/idp-setup/microsoft-entra-saml-setup.md
Minor changes for consistency and small typo fixes (admittedly pedantic at times) benefiting from fresh perspective.
> Minor improvements to Enterprise SSO section

- pages/learn/manage/actions.md
- pages/reference/api/overview.md
> patch: Fix broken links after accounts section added

- pages/learn/develop/apps.md
> Add a note on experimental feature flag to the apps documentation

- pages/learn/develop/container-contracts.md
> Add additional container contracts info

- static/_headers
Add a security _headers file to propogate it to Cloudflare Headers
> patch: Add _headers file

- pages/reference/supervisor/configuration-list.md
> patch: Remove balena suffix from configurations list

- config/dictionaries/resource.json
> API/resources: Add docs on how to retrieve device env vars & device service env vars by device UUID

- config/dictionaries/resource.json
> API/resources: Retrieve the service name as part of the device service env var GET requests

- config/navigation.txt
> patch: Fix FAQ questions page in navigation sidebar

- config/redirects.txt
> patch: Add default FAQ redirect for troubleshooting

- .github/workflows/deploy-to-cloudflare-pages.yml
- .github/workflows/flowzone.yml
- .github/workflows/link-checker.yml
> CI: Update checkout settings

- pages/learn/accounts/enterprise-sso.md
> patch: state that SAML is available to all standard paid plans

- pages/learn/welcome/security.md
Link to our trust center at `trust.balena.io`
---
> Add section `Trust and Transparency` to the Security Page

- config/dictionaries/resource.json
> API/resources: Add an example for retrieving the fleets of a specific organization

- .cspell/computer-terms.txt
- .husky/pre-commit
- README.md
- config/redirects.txt
- package-lock.json
- package.json
- tools/build.sh
- tools/convert-images-to-webp.sh
Discussion: https://balena.zulipchat.com/#narrow/stream/345890-balena-io/topic/Updating.20images.20.28PNGs.29.20in.20the.20documentation/near/475294574
---
> Convert images on deploy time instead at pre-commit

- config/dictionaries/resource.json
- pages/reference/api/overview.md
Change-type: major
See: https://balena.fibery.io/Work/Task/API-resources-Change-the-requests-to-use-the-v7-endpoint-2258
> API/resources: Change the requests to use the v7 endpoint

- config/dictionaries/resource.json
> API/resources: Add the device.shoud_be_running__release field & example use

- pages/learn/manage/actions.md
> actions: Fix device's Restart Services action being Restart Fleet

- .cspell/balena-words.txt
- .gitignore
- config/navigation.txt
- config/redirects.txt
- pages/reference/sdk/node-sdk.md
- templates/balena-sdk.html
- tools/build.sh
- tools/fetch-external.sh
Followed by the versioning PR to create versioned docs for NodeJS SDK
> Create versioned docs for balena Node.js SDK

- tools/build.sh
- **Before Improvement**: 82.30 seconds
- **After Improvement**: 60.25 seconds
- **Total Time Improvement**: 22.05 seconds (26.8% reduction)
| Metric | Before Improvement | After Improvement | Improvement |
|--------|---------------------|-------------------|-------------|
| Total Time | 82.30 seconds | 60.25 seconds | 22.05 seconds ↓ |
| User Time | 25.18 seconds | 25.07 seconds | 0.11 seconds ↓ |
| System Time | 49.69 seconds | 51.16 seconds | -1.47 seconds ↑ |
> Perf: Decrease docs build time 

- pages/learn/deploy/deploy-with-balena-button.md
> Update the balena.yml docs to mention full semver support

- pages/learn/welcome/introduction.md
> Update feature requests page link

- templates/_machines-architectures.html
Updated the query to fetch the right device types from the API
> patch: Update query to fetch device types

- pages/learn/deploy/deployment.md
> patch fix typos in deployment.md

- pages/learn/develop/multicontainer.md
Improve some texts and link to update status documentation
> Container requirement documentation tweaks

- pages/reference/OS/overview.md
> Update Avahi Documentaiton to add Port Details

- pages/reference/supervisor/docker-compose.md
> supervisor docker-compose: Move `expose` to Known unsupported fields

- pages/learn/manage/device-statuses.md
> patch: Fix broken link for Container Requirements

- config/dictionaries/language.json
> patch: Remove Haskell from Getting Started languages

- pages/learn/deploy/build-optimization.md
- pages/learn/more/anti-patterns.md
> Replace balenalib references in favor of Docker Official images

- pages/learn/welcome/security.md
> Remove balena base image sentences

- pages/learn/welcome/primer.md
> Remove link to balenalib on DockerHub

- config/links.coffee
- config/names.coffee
> patch: Remove balenalib references from config

- pages/reference/base-images/balena-base-images-reference.md
> Create balenalib base images reference documentation

- pages/learn/accounts/billing.md
> Update billing.md to suggest that Inactive devices are powered off

- .cspell/balena-words.txt
- .cspell/computer-terms.txt
- pages/learn/develop/dockerfile.md
> Update dockerfile.template section of develop/dockerfile/

- shared/getting-started/cliInstructions/_default.md
> Update getting started docs for cli

- pages/reference/base-images/balena-base-images.md
> Fix digest syntax

- tools/versioning.js
✅ With GitHub Token: Gets real version data (3 versions each)
✅ Without GitHub Token: Creates valid fallback (1 "latest" version each)
✅ Build Always Succeeds: No more "Unknown key $balenacli" errors
> patch: Account for ratelimits on releases API

- tools/fetch-external.sh
> patch: Add errors for rate limited URLs
