balena-io/docs

pages/troubleshooting/troubleshooting.md

If drivers are not installed, I get:
dfu-util: Device has DFU interface, but has no DFU functional descriptor

Document the need of Edison drivers on Windows

---

pages/installing/gettingStarted-NUC.md

Changed all the mentions of SD card to USB key in the getting started with NUC as per [issue 120](https://github.com/resin-io/docs/issues/120).

[gettingStarted-NUC.md] removed mention of SD cards

---

pages/configuration/advanced.md

(Should only be merged after the new env var UI is deployed)

Document modifying config.txt with env vars

---

pages/runtime/resin-base-images.md

I didn't find any info on:
- RPI1 model A (not supported?)
- RPI zero (not supported?)
If supported, they should be listed as well

Some corrections to make Raspberry Pi 3 easier to find

---

config/navigation.txt
pages/introduction.md
pages/runtime/resin-base-images.md
pages/tools/cli.md

Increase prominence of Resin Base Images Wiki
Previously this was not so easily accessible, these changes rename the page to make use of the phrase 'base image' which is the more commonly known name for images, add a link to the page on the references tab and add a blurb about base images with a link to the introduction page.
Solves issue #248.

Make images wiki prominent

---

pages/runtime/bandwidth-reduction.md

The line ending `|` was not included in the table. On the web the
generated pages were okay, but eg. on Github the markdown table
did not show properly. Fix it up for future proofing.

fix up table to proper markdown

---

pages/runtime/runtime.md

I think it will be better if we add the environment file in the example service file since many users asked about this

Improve runtime document: add environment file to systemd service

---

pages/integrations/artik.md

The ARTIK API has changed from the previous (2.0.3) version to the current (2.0.5), making our examples invalid. Fix them up.

update Artik example code

---

config/navigation.txt
pages/examples.md
pages/integrations.md

Some of the categories are harder to understand, when clicking on the header
in the navigation bar takes the user right to the first item in the category.
It makes the other items in the category easy to miss in our navigation bar.
Add some category pages, from where the rest of the items are linked.

add some category header pages

---

pages/runtime/runtime.md

Changes:
* add example of querying whether the device is NTP synchronized (actually came up in support, and it is different from the other two examples as it returns data)
* adjust formatting of `dbus-send` commands for better readability
* fix missing ling as per #332

dbus updates

---

pages/runtime/runtime.md
shared/diveIntoCode/cpp.md
shared/diveIntoCode/go.md
shared/diveIntoCode/nodejs.md
shared/diveIntoCode/rust.md

Switch from using `=`, and make sure everywhere used the same way.
Connects to #335.

Standardize on `ENV VARNAME value` format in Dockerfiles

---

pages/runtime/data-api.md

This PR tries to fix the confusion that arise when Payload is Mixed with Param
From my understanding, we use Param to specify parameters that are passed with the URL.  This can be query params after the ? part of the URL or some placeholder in the case of something like `/device(<ID>)`.
On the other hand, what is written in the request body is Payload, which in the cURL examples are passed with the `-data` flag`.

Distinguish Param from Payload

---

config/index.coffee

So that it matches what https://resin.io/ does

Update "Community" link

---

pages/hardware/i2c-and-spi.md

This PR documents how to disable HDMI on the Beaglebone Black so one can make use of all the GPIO pins on the device.

add info on disabling hdmi on BBB

---

pages/hardware/i2c-and-spi.md

This PR adds info on using UART0 on the rpi3 and is associated with this demo project: https://github.com/resin-io-playground/rpi3-uart
It closes issue #265

Rpi3 hardware

---

pages/runtime/migrate-to-2.0.md

Path has not been deprecated - in recent releases it's been entirely moved.

Clarify ResinOS 2.0 dbus migration instructions

---

pages/hardware/devices.md
shared/whatYouNeed/jetson-tx2.md

Temporarily add banners in getting starting guide and supported device list to note that TX2 support is temporarily unavailable.

Warning banners for Jetson TX2

---

pages/hardware/wifi-dongles.md

Fix link to RPi official WiFi dongle

---

config/doxx.coffee
config/index.coffee
config/links.coffee
config/names.coffee
package-lock.json
package.json
pages/reference/sdk/python-sdk.md
server/index.coffee
templates/default.html

The path defaults to /docs, but can be overridden by setting
`PATH_PREFIX` as an env var. To actually work, this will require a newer
version of resin-io/doxx. PR coming for that repo.
Change-type: major
Signed-off-by: Jack Brown <jack@balena.io>

Modify the repo to support serving content on a subpath

---

static/scripts/main.js
templates/_track.html

I had to export jQuery from the main script so I could access it in the
Mixpanel snippet in order to request `/config`.
We're also changing the host where we post Mixpanel events to, as we are
now going to have all events going through the API.

Mixpanel: Dynamically get the token from api.resin.io/config

---

config/dictionaries/resource.json
config/links.coffee

This adds an example expanding from application to devices, after a user (https://app.frontapp.com/open/cnv_11nbptv) pointed out that that wasn't documented.
This PR also changes the default `API_BASE`. Everywhere expects this to not have a trailing slash, and it doesn't appear to in production, but in dev every generated URL ends up with a double slash here before this change.
Fixes #917

Add owns__device to the application resource, and fix local dev URLs

---

config/redirects.txt

Fixes the following redirects:
* https://docs.resin.io/nuc/nodejs/getting-started/
* https://docs.resin.io/dart6ul/nodejs/getting-started/
* https://docs.resin.io/beaglebone/nodejs/getting-started/
* https://docs.resin.io/raspberrypi/nodejs/getting-started/
* https://docs.resin.io/raspberrypi2/nodejs/getting-started/
Couldn't figure out how to fix:
https://docs.resin.io/#/pages/installing/gettingStarted-ODROID-C1.md#windows
https://docs.resin.io/#/pages/installing/gettingStarted-ODROID-XU4.md#windows
Trying to match the `#` wasn't working as expected.
Connects-to: #958

config/redirects: Fix unescaped and device type alias redirects

---

pages/reference/base-images/base-images.md

Escape characters in markdown formatting

---

templates/_track.html

analytics: Fix broken mixpanel reporting

---

config/dictionaries/resource.json

We originally used `env_var_name` as a field on those resources,
but we ended up adding a translation before announcing this API
version, so that all env var resources have the same base fields.
Resolves: #978
See: https://github.com/balena-io/resin-api/pull/832
See: https://github.com/balena-io/resin-api/blob/a8f53ce3ffce55cfc64e16e5d016eab5520a9cc2/test/06_device_environment_variable.coffee#L45
See: https://github.com/balena-io/resin-api/blob/a8f53ce3ffce55cfc64e16e5d016eab5520a9cc2/test/06_device_environment_variable.coffee#L87-L89

resources: Fix app & device envvars to use the translated name field

---

server/index.coffee
static/css/main.css
templates/_search-form-mobile.html
templates/_search-form.html

The algolia input was under a form. Before algolia would load, this form
could be submitted, resulting in an undesired redirect.
Connects-to: #1024

Prevent algolia input from from being submitted

---

pages/404.md
server/index.coffee
templates/_algolia.html
templates/not-found.html

In order to fix the issue I made the 404 page also be served
by Doxx, fixing the issue with the wrong routing of the css and 
js files. This one was very annoying, I am so glad it got fixed.
Connects-to: #940

Fix the 404 page from not displaying correctly

---

pages/reference/cli.md
pages/reference/sdk/node-sdk.md
pages/reference/sdk/python-sdk.md
pages/reference/supervisor/supervisor-api.md

* Make the standalone installer the recommended option.
* Move installation instructions to a new INSTALL.md in the CLI repo.
* Also patch updates for the Node SDK, Python SDK and the Supervisor.
Btw, FYI, there is an open CLI PR implementing review changes requested by @hedss: 
https://github.com/balena-io/balena-cli/pull/1200
Signed-off-by: Paulo Castro <paulo@balena.io>

Update ref docs for the CLI, Node SDK, Python SDK and Supervisor

---

pages/reference/base-images/base-images.md

- Update latest stack changes.
- Update some notices for node images regarding some versions or architecture were dropped.

baseImages: Update base images docs

---

pages/learn/manage/serv-vars.md
pages/reference/OS/advanced.md

remove spurious trailing spaces

balena sync: standardize references to `.balena-sync.yml` config

---

pages/learn/manage/configuration.md

We add docs for the RESIN_SUPERVISOR_INSTANT_UPDATE_TRIGGER variable, and expand on the description of the RESIN_SUPERVISOR_POLL_INTERVAL variable.

configuration: add docs for disabling instant updates

---

pages/learn/manage/account.md

Fixes #1141 
Documentation says that the operator can add a new device. But it's not allowed, because the operator can't select the OS version.
User was confused by this, see https://jel.ly.fish/4dee4de8-d26a-4733-8f93-1a125fd85442
Signed-off-by: Robert Vojta <robert@balena.io>

management: Operator is not allowed to add new device

---

pages/faq/troubleshooting/faq.md
shared/network/2.x.md

Whitelisting Mixpanel should be no longer necessary.
Signed-off-by: Michael Angelos Simos <michalis@balena.io>

Update network requirements

---

pages/reference/base-images/base-images.md

The example for building an ARM image on an x86 machine was using the outdated resin base image and installed python instead of python-pip

Fix the example Dockerfile for crossbuilding

---

pages/reference/OS/time.md

Note: far from complete pull request.
This is just a hint that the documentation is outdated. The document probably needs further adjustment.

resin 2.13 uses `chrony` (vs `systemd-timesyncd`)

---

pages/reference/base-images/base-images.md

component: Add version numbers to Ubuntu version names
Signed-off-by: Jason Harrison <jason@eiodiagnostics.com>

Adding version numbers to Ubuntu versions

---

templates/_track.html

This fixes some skipped device IDs in generated dashboard URLs.
Update analytics-client from 0.1.0 to 0.1.1
See balena-io/analytics-client#2

Bump analytics client

---

pages/learn/deploy/release-strategy/update-locking.md

The current snippet has `lock` on the end of the path, which results in a lockfile called `updates.lock.lock`, which does not have any effect on updates.

Correct Python snippet

---

pages/learn/more/masterclass.md

Not to be merged until https://github.com/balena-io-projects/balenaos-masterclass/pull/2 is in

docs: Adding link to balenaOS masterclass

---

pages/reference/OS/meta-balena.md

Closes #1225 
This is the content from https://www.balena.io/os/docs/custom-build/#Supporting-your-Own-Board. Content on https://github.com/balena-io/resin-site is private so not currently suitable for `fetch-external.sh`. This at least removes the outdated content.

docs: Updating content for custom board support

---

pages/learn/more/masterclass.md

Not to be merged until https://github.com/balena-io-projects/balena-fleet-management-masterclass/pull/1 goes in.

docs: Adding link to fleet management masterclass

---

pages/learn/develop/multicontainer.md

This setting was removed as I understand. There is this section https://www.balena.io/docs/reference/base-images/base-images/#installing-your-own-initsystem in the docs as well as this masterclass section https://github.com/balena-io-projects/services-masterclass#5-running-systemd-in-a-service for running systemd in a container.

docs: Removing outdated initsystem references

---

shared/network/2.x.md

Closes #1275 
Connects-to: 1275

docs: Fixing broken link to base images

---

package-lock.json
package.json

Bump merge from 1.2.0 to 1.2.1
Bump jquery from 3.4.0 to 3.4.1
Bump lodash from 4.17.13 to 4.17.15
Tested on staging site https://www.balena-staging.io/docs/learn/welcome/introduction/

deps: Bump all dependabot dependencies

---

pages/learn/develop/integrations/aws.md

- The `AWS_PRIVATE_CERT` and `AWS_THING_CERT` environment variables values were swapped
Signed-off-by: Rahul Thakoor <rahul@balena.io>

Fix error in values for AWS_PRIVATE_CERT and AWS_THING_CERT

---

config/links.coffee
shared/general/deviceTypeNames.md

This PR updates this page https://www.balena.io/docs/reference/base-images/devicetypes/ for all supported device types. This is generated from the contracts repo using this simple Python snippet https://gist.github.com/garethtdavies/00f9c361d0b9f274f8c9bf452c6f9603
More discussion here: https://www.flowdock.com/app/rulemotion/i-baseimages/threads/J9S58kUKH8Z35I2EvhCm1VpaO-K

docs: Update base image machine types

---

config/links.coffee
pages/reference/base-images/base-images.md

@nghiant2710 I've manually updated the base image page for updated version information and to get a better sense of how it works before trying to pull this information in dynamically from the contracts.
I wrote a simple script to parse the `version` field for each variant from here for Node.js for example https://github.com/balena-io/contracts/blob/master/contracts/sw.stack/node/contract.json. A couple of questions as result:
* There are some images that do not have contracts but do exist in DockerHub, specifically Node 10.10 which is referenced in these docs https://hub.docker.com/layers/balenalib/raspberrypi3-debian-node/10.10.0-stretch-run/images/sha256-15c6d3683496a4813d487e79796f30debf1a637a42ebca258c3b6224ea15784f. As I understand these point to the corresponding frozen date image. …

baseImages: Updating base image versions

---

package.json

This closes #1247 💥 Fixed via this commit in Doxx repo https://github.com/balena-io/doxx/pull/29
Connects-to: #1247

meta: Fix excerpt tag expanding variables correctly

---

config/redirects.txt

This actually fixes the redirect. It's a hacky fix as there is a double redirect going on as it first strips the file extension. Given this is coming from an upstream repo I don't think there is too much else that can be done unless anyone has any good ideas?
Closes: #1154

meta: Fix Supervisor API redirect

---

shared/general/host-ssh.md

Some updates to the second half of the SSH page which deals with troubleshooting.  This might eventually make sense on its own page but for now, I’ve updated what it there.
This is largely taken from WIP debugging masterclass and the host OS masterclass but I think this info really needs to be in the docs.

docs: Updating SSH troubleshooting

---

templates/_track.html

In December, mixpanel client update broke our reporting because it switched from
GET to POST. GET is not handled by our backend.
This change forces the supported method to be used.

Fix page views reporting

---

shared/overview/2.x.md

Lots of updates required on [this page](https://www.balena.io/docs/reference/OS/overview/2.x/) and here is the first batch (up to BalenaOS Components) which touches a number of existing open issues.
Connects-to: #1314
Connects-to: #1016
Connects-to: #1129
Connects-to: #1091

os: Updating host OS variants

---

shared/general/container-ssh.md
shared/general/host-ssh.md

Updating links to point to the docs site which expands the content of `config.json` and will pull in the upstream content (when #1317 lands and https://github.com/balena-os/meta-balena/pull/1804 reaches master)

meta: Updating links to config.json to use docs site

---

shared/overview/2.x.md

Refreshing the final section of this page https://www.balena.io/docs/reference/OS/overview/2.x/ for Yocto.
I've tried to simplify what was there but suggestions and feedback for anything else that needs to be covered in this brief overview are welcome.
Connects-to: #1035

yocto: Update Yocto references for hostOS

---

shared/general/deviceTypeNames.md

Ref: https://github.com/balena-io/contracts/pull/143
The table is also formatted hence the diff output.

base-images: Adding nitrogen8mm-dwe to machine names and architectures

---

pages/faq/troubleshooting/troubleshooting.md

troubleshooting: Add instructions for TX2 failure when flashing  newer L4T versions

---

pages/reference/supervisor/docker-compose.md

I tried using it and got an error with `...should NOT have additional properties`. This is because `init` is part of DC `2.2` and we use `2.1`

Remove unsupported docker-compose property ("init")

---

pages/learn/deploy/release-strategy/release-policy.md
pages/learn/develop/local-mode.md
pages/learn/develop/runtime.md
pages/learn/more/anti-patterns.md
pages/learn/welcome/production-plan.md
pages/reference/OS/configuration.md
shared/general/host-ssh.md

Updates to keep links to masterclasses on the docs site.

meta: Update masterclass links to point to docs site

---

pages/learn/develop/runtime.md

Added an additional example via https://github.com/balena-io/balenaos-masterclass/pull/8

meta: Link to OS masterclass for additional dbus examples

---

config/dictionaries/resource.json

Added a missing resource of application tag. 
Is there an endpoint that lists all available resources or where would be the easiest place to look to track down any additional missing endpoints?

reference: Update API resources for application tag

---

config/dictionaries/device.json

Based on the internal discussion here: https://www.flowdock.com/app/rulemotion/resin-devices/threads/kpB0Ea03TYV973gdqY_WPAUOkAL

Remove IoT2000 from Getting Started Guide

---

config/dictionaries/resource.json
shared/apiGeneral/calls.md

Closes #1418 
Added some extra examples for `my_application` resource and clarification that `application` will return public applications. On the resources page, I added this under the `application` resource as didn't want to duplicate it all as a separate `my_application` resource but I can do this if further clarification is required.

Adding details for my_application resource

---

config/navigation.txt
pages/reference/sdk/.gitignore
pages/reference/sdk/deprecation-policy.md
shared/sdk/.gitignore
tools/fetch-external.sh

Depends-on: https://github.com/balena-io/balena-sdk/pull/892
This will pull in the SDK deprecation policy as a partial. Requires balena-io/balena-sdk/pull/892 to be merged as pulling from master. Tested the above branch and looks like this:

Pull in SDK deprecation policy

---

pages/learn/develop/container-contracts.md

Splitting #1385 into two (will close that PR) as only these changes made it into balenaOS 2.49.

Updating container contracts for optional semantic versioning matching

---

config/dictionaries/resource.json

Closes #1412 
These could likely do with some further explanation, e.g. an API masterclass but added examples for now and also added the application membership role resource.

Adding user management API examples

---

templates/_devices.html

The getting started still uses a .json as a source of truth, but at least this one is out of the way.

Use S3 logo URL for supported device types

---

templates/_devices.html

Earlier I didn't run it in watch mode and I thought all of them work :/
It turns out we still don't have logos in S3 for all device types (when I ran it without watch mode, it seemed like there are for all of them), and half-baked solution will only make it more messy than it already is.
Once we resolve the issue on where the images are stored and we have fully
migrated to it, I'll revisit this.

Revert using S3 images for supported device types

---

pages/learn/develop/container-contracts.md

Second commit from #1385 
This shouldn't be merged until supervisor 11.1.0 is included in an OS release.

Updating container contracts for matching on hardware type

---

.gitignore
CONTRIBUTING.md
config/index.coffee
config/links.coffee
config/navigation.txt
tools/fetch-external.sh

This includes documentation about supervisor upgrades in the docs website; this documentation was introduced [here](https://github.com/balena-io/balena-supervisor/pull/1376).
Note: instructions about how to perform the upgrade, along with a discussion of version constraints, will be added once https://github.com/balena-io/balena-ui/pull/3434 is merged.    
Connects-to: https://github.com/balena-io/balena/issues/2157
Signed-off-by: Hugh Brown <hugh@balena.io>

Add supervisor upgrades doc

---

pages/reference/base-images/base-images.md

Pushing an ARM arch app with this config on native builders lead to errors. To avoid this we recommend users to not push this to balena builders, instead build the image on x86 systems.
@ab77 :eyes: 
Solves #1134

Add caveat for building ARM containers on x86

---

pages/learn/develop/runtime.md

This makes explicit which key should be used to determine whether a device is synchronized via NTP:  `NTPSynchronized`, not `NTP`.  This reflects the info at https://www.balena.io/docs/reference/OS/time/ -- however, that page refers to this one to show the DBus query to run to check synchronization, so it's good to have it here as well.
Signed-off-by: Hugh Brown <hugh@balena.io>

Make explicit which key to use to determine NTP synchronization

---

pages/learn/manage/configuration.md

These no longer apply on more recent OS releases and can cause confusion.

Remove mentions of legacy deltas config variables

---

pages/reference/base-images/legacy-base-images.md
shared/network/2.x.md

This clarifies that the `python-dbus` module is only included in python `-build` image.
Connects-to: #1505
Connects-to: https://github.com/balena-os/balena-os/issues/552
Signed-off-by: Hugh Brown <hugh@balena.io>

Make clear that python-dbus is only included in -build images

---

shared/network/2.x.md

[nm-settings-ref] was attempting to link to
https://developer.gnome.org/NetworkManager/stable/nm-settings.html
whereas the best match URL now seems to be
https://developer.gnome.org/NetworkManager/stable/ref-settings.html

2.x.md: fix broken nm-setting-ref link

---

pages/learn/deploy/deploy-with-balena-button.md

Hotfix: Update balena.yml v2

---

shared/network/2.x.md

networking: devices no longer require access to DockerHub

---

pages/reference/OS/updates/self-service.md

since any MC-capable device can be upgraded to any other host OS, let's
drop these references.

host OS updates: drop specific DT upgradability references

---

.github/CODEOWNERS

meta: remove some outgoing codeowners

---

config/redirects.txt

The regex that matches root path did not match if any parameters were added. This caused the docs to redirect to 404 if you visit website.com/docs?thing=1.
I also made sure that parameters are added to the redirected URL.

Prevent params in URL from breaking redirect rules

---

pages/reference/OS/advanced.md
shared/overview/2.x.md

The OS is rebranding the splash image file from v2.51 onwards.
Signed-off-by: Alex Gonzalez <alexg@balena.io>

Rename resin-logo.png to balena-logo.png

---

config/navigation.txt
pages/learn/deploy/offline-updates.md

Add Offline Updates documentation

---

pages/learn/deploy/delta.md

Clarify that devices running new balenaOS versions (2.47.1+ / ESR 2020.04+) will ignore fleet-wide delta configuration.
Signed-off-by: Tomás Migone <tomas@balena.io>

deltas: clarify deltas by default behaviour with fleet wide vars

---

pages/learn/deploy/deployment.md
shared/general/container-ssh.md

Also, link to the procedure on how to add an SSH key to the account.
Signed-off-by: Carlo Miguel Cruz <carloc@balena.io>

Make it clearer that "balena ssh" requires adding an SSH key to balenaCloud.

---

config/navigation.txt

component: Fix `Microsoft Azure` link in the sidebar
Signed-off-by: Genadi Naydenov <genadi@balena.com>
Resolves #1631

Fix MS Azure link in the sidebar

---

shared/network/2.x.md

Section should now reflect that the preferred method for enabling
redsocks is through the related Supervisor endpoints. Links have
been added. If the user prefers to not use the endpoints, the docs
for adding redsocks without touching the Supervisor API have also
been clarified.
Signed-off-by: Christina Wang <christina@balena.io>

Update proxy documentation section

---

pages/reference/hardware/wifi-dongles.md

- Remove discontinued dongles
- Add some common TP Link dongles
- Shuffle some sections around
- Related meta-balena PR to remove "Official RPI WiFi" link: https://github.com/balena-os/meta-balena/pull/2138
Closes: #1277, #602
Signed-off-by: Tomás Migone <tomas@balena.io>

wifi-dongles: update list

---

shared/network/2.x.md

Resolves issue #1659 for shared Ethernet example using Network Manager config file.
Signed-off-by: Alex Bucknall <alexbucknall@balena.io>

Adds shared Ethernet example for NM, under 'Networking'

---

pages/learn/deploy/delta.md

User can no longer disable delta updates.
Connects-to: #1674
Signed-off-by: Pranas Ziaukas <pranas@balena.io>

Disable the note about disabling deltas

---

pages/learn/develop/multicontainer.md

https://github.com/balena-io/docs/issues/785
https://github.com/balena-io/balena-io/issues/1297
Changelog-entry: Clarify the depends_on behavior in multicontainer apps

Clarify the depends_on behavior in multicontainer apps

---

Dockerfile
package.json

This avoids potential issues with unexpectedly updating the nodejs
version

Pin the base image to nodejs 14 LTS

---

.github/workflows/link-checker.yml

Fixes #1621
This PR adds a GitHub action that will scan the codebase for broken
links once a week on Monday.
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

Add a periodic GitHub action to scan markdown files for broken hyperlinks

---

shared/getting-started/getDeviceOnDash/beaglebone-black.md

Remove old resin dashboard screenshot from Getting Started Guide

Remove old resin dashboard screenshot

---

.gitignore
config/doxx.coffee
server/index.coffee

This should significantly speed up builds

Stop generating lunr index as we no longer use it

---

pages/reference/base-images/base-images.md

- Clarifying that you are not limited to the languages pre-installed in base images - you can use any language that you can later install in your image/container
- Clarifying that Dotnet is valid for <lang_stack>, i.e. making consistent with the earlier bullets under “Multiple language stacks”
- Noting that Python 2.7 is deprecated as per https://www.balena.io/blog/deprecation-of-python-2-base-images-in-balenalib/. This specific change was suggested by vipulgupta2048
Signed-off-by: Ross Porter <ross@balena.io>
Closes #1498

Clarifying wording about language stacks

---

pages/reference/OS/extended-support-release.md

Added details:
* RPi v1 / Zero (+ /ZeroW)
* specified BB Black (not Green, etc.)
* specified Fin CM3 (in anticipation of CM4 model)
ESR support for Nano does not appear to exist though, so keeping it excluded from the list for now. Have asked for confirmation of where he saw support from reporter (dtischler) and will submit another PR if it is indeed supported.

Updated ESR List

---

config/dictionaries/device.json

Added Jetson Xavier NX SD-Card Device Type for Getting Started Guide, re-using the Jetson Nano as a starting point.
Signed-off-by: David Tischler <david@balena.io>

Added Jetson Xavier NX SD-Card Device Type

---

tools/fetch-external.sh

By parallelizing downloads, we ended up going so fast that DOCUMENATION.md files downloaded from the sources ended up being overwritten before being moved to their right location. This led us into a weird state of the Python SDK having NodeSDK docuentation. Resolved it by moving SDK download out of the parallel download.

Patch fetch-external script to not parallelize SDK docs

---

shared/network/2.x.md

To prevent customers being confused about the location of files they need to edit in the boot partition, I've specified the location in a note below the second paragraph.

Specify File Location for NM

---

templates/devices.html

I was searching for supported devices on the docs and could only find the ESR list, with this change it should be much easier to find the list of regular supported devices

Specify "currently supported *devices*" to make it easier to search for

---

package.json
tools/fetch-external.sh

Adds the jq installation as part of the heroku-prebuild script.
Signed-off-by: Carlo Miguel Cruz <carloc@balena.io>

Heroku: Install jq as part of the build runtime.

---

package.json

Signed-off-by: Carlo Miguel Cruz <carloc@balena.io>

Switch to Node12 and remove Heroku prebuild script.

---

shared/getting-started/getDeviceOnDash/coral-dev.md

Some units will boot from the SD-CARD only
if all bootswitches are set to off, as
reported by some of our users. Let's include
this information in our docs as it might help
troubleshoot flashing.
Fixes: https://github.com/balena-io/docs/issues/1519

coral-dev: Mention alternate sd-card bootswitch configuration

---

pages/reference/OS/time.md

TODO before merging
I am dumping my research here, 
1. Seems hacky but worked: https://unix.stackexchange.com/a/158721 on Fedora
2. [FD thread](https://www.flowdock.com/app/rulemotion/r-beginners/threads/yaZqcalZ6Ewfx73YsEZ-dU93M-2)
3. [Forums](https://forums.balena.io/t/timezone-troubles/122430/4)
I have to figure this out.

Patch: Add TZ env var to set timezone in container

---

pages/learn/develop/hardware/i2c-and-spi.md

Updated the camera fleet variable names to what I needed to do to get camera working with the latest version. I also used the extra variables found [here](https://www.balena.io/blog/build-a-raspberry-pi-based-network-camera/#configuration:~:text=Configuration,-Must%2Dhave).
---

Update Camera Fleet Variable names

---

package-lock.json
package.json
static/scripts/langs.js
static/scripts/main.js
webpack.config.js

* Update dependencies
> Used the npm-check-updates tool
After this npm finds
10 vulnerabilities (6 low, 4 high)
* Remove and replace deprecated module with alternative
> More info:
https://www.npmjs.com/package/extract-text-webpack-plugin
* Remove unused package metalsmith-prefixoid
After this npm finds
9 vulnerabilities (6 low, 3 high)
All the vulnerabilities left come from @balena/doxx
Connects-to: https://github.com/balena-io/docs/issues/1665
Signed-off-by: Marios Balamatsias <mbalamatsias@gmail.com>

Fix most of the vulnerabilities

---

shared/getting-started/getDeviceOnDash/intel-nuc.md

As described in #1816, my brand new Intel NUC 8i5BEH arrived with Secure Boot enabled, which resulted in an error at boot time. I don't know how likely it is for a user to encounter this error, but the severity is high because you can't even install the OS. 
This PR adds a Note to the Getting Started instructions that describes how to use the BIOS utility to disable secure boot and continue with balena OS installation. I also added another small commit to reflect the name shown for the USB device in the Intel Boot Menu.
I don't know our policy on documenting an error like this. Does the chance of a user encountering it justify breaking the flow for other users on the success path? I wrote the PR, so I'd say Yes, but leave it to the reviewers for a judgement.
Closes #1816

Intel NUC Getting Started secure boot note

---

shared/network/2.x.md

* includes example app to configure on-device proxy automatically
* includes examples hosting the proxy server on AWS and DigitalOcean
---

Add proxy-tunnel project reference

---

shared/general/deviceTypeNames.md

It is currently only supported under private device types.
Connects-to: #1807
Signed-off-by: Pranas Ziaukas <pranas@balena.io>

Remove "Zynq zc702" from publicly supported devices

---

pages/reference/base-images/base-images.md

A broken link on base images/installingyourowninitsystem
Broken url: https://github.com/balena-io-library/base-images/tree/master/examples/INITSYSTEM/systemd/systemd.v230/balena.service
Correct link: https://github.com/balena-io-library/base-images/blob/master/examples/INITSYSTEM/systemd/systemd.v230/resin.service
---

Patch: Fix broken link

---

.github/dependabot.yml

This is so we can easily merge PRs from dependabot like https://github.com/balena-io/docs/pull/1914 without having to checkout the branch and fix versionbot.
dependabot config options https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

Added dependabot config to format commit messages

---

config/navigation.txt
pages/reference/supervisor/bandwidth-reduction.md
pages/reference/supervisor/device-metrics.md

Metrics include CPU temp, CPU usage, memory usage/total,
storage usage/total, CPU ID. Metrics are categorized by optional
system metrics that aren't reported when SUPERVISOR_HARDWARE_METRICS
is false, and system checks that are always reported regardless of
SUPERVISOR_HARDWARE_METRICS's value.
Closes: #1901
Signed-off-by: Christina Wang <christina@balena.io>
---

Add device metrics docs

---

package-lock.json
package.json

reverts https://github.com/balena-io/docs/pull/1949 which introduced some breaking changes that caused the docs to not render correctly
---

Downgrade boostrap from 5.0.2 to 3.4.1

---

templates/api.html

The only way to navigate to this page is by going to Reference -> API -> Resources. This is extremely unintuitive since I personally keep forgetting the path and always just find things in the docs via the search bar. This page is not indexed in the search by correctly because the page does not mention what it is. This PR adds a heading which will allow the search bar to index the page and return it when someone enters "API", "balenacloud api" "cloud api" etc.

Added heading to describe balenaCloud API resource page

---

README.md

I felt this was needed to clarify whereto  find the mechanism which deploys the docs and how to go about making modifications if needed. Previously the readme just mentioned that the docs will be deployed automatically without explaining how.

Clarify where deployments are performed

---

pages/learn/develop/runtime.md

The current link takes you to the correct page, but the anchor tag for the section is incorrect.
Signed-off-by: Mark Corbin <mark@balena.io>
---

Fix link to Supervisor API reference

---

.github/workflows/link-checker.yml

We don't want to exclude return code 429 as that may
mask issues with dead links.
Also, the way this flag was added broke the usage of
the --exclude flag by mistake.
See: https://github.com/balena-io/docs/issues/1972
Partially reverts: https://github.com/balena-io/docs/pull/1964

Resume checking for rate-limit return codes

---

package-lock.json
pages/learn/manage/device-statuses.md

Attempted to make the device status page clearer for users, and to include more explicitly the `VPN Only` and `Heartbeat Only` statuses.
Moved images to end of document, as they don't seem to be very useful, other than an example.
Signed-off-by: Scott Lowe <scott@balena.io>
---

Improve device status page

---

pages/learn/deploy/deployment.md

I moved around a bunch of text and made sure not to mix the features of
`build` into the sections about `deploy` (even though functionally that
makes sense).
Also linked to the cli reference at the end of each part (since that
documents the options in much greater detail).
Connects-to: https://github.com/balena-io/docs/issues/550
Connects-to: https://github.com/balena-io/balena-cli/pull/2272
Signed-off-by: Robert Günzler <robertg@balena.io>

Rework the build/deploy section

---

pages/reference/OS/time.md

Add a clarification to the time management documentation stating that UDP port 123 only needs to be open for outgoing connections from the device.
Signed-off-by: Mark Corbin <mark@balena.io>
---

Update time management UDP port details

---

pages/learn/getting-started.md
shared/getting-started/cliInstructions/_default.md

This adds more information to the `Getting Started` guide by breaking out the CLI into it's own section. Each OS specific section has links to the latest CLI release tag pulled from github.

Adding detailed CLI installation instructions to getting-started

---

config/navigation.txt

Removed this link because it's been superseded by https://github.com/balena-io/docs/blob/master/pages/reference/supervisor/supervisor-upgrades.md#upgrade-paths

Remove "Upgrade Policy" link for device Supervisor

---

pages/reference/supervisor/docker-compose.md

Occasionally users try to use fields that are supported by v2 but have
different properties in version >=2.2 (like long syntax for ports/volumes) and
are surprised to get an error in response.
Clarify that our support is based on version 2.2
Signed-off-by: Robert Günzler <robertg@balena.io>
---

Mention compose file version in the supervisor docs

---

config/redirects.txt

Because of https://github.com/balena-io/docs/pull/2068 any links to the upgrade policy will 404 and I think that page is probably linked enough to warrant a redirect which I didn't think of until after.
Redirects https://balena.io/docs/reference/supervisor/upgrade-policy -> https://www.balena.io/docs/reference/supervisor/supervisor-upgrades/

Redirect Upgrade Policy links to self-service upgrades

---

config/dictionaries/device.json

Namely, insturctions, machine and state were properties aren't being used anywhere
in the documentation and hence were removed.
---

Drop unused properties from device.json

---

shared/general/container-ssh.md

See: https://jel.ly.fish/support-thread-1-0-0-front-cnv-bc3ywb1
Connects-to: balena-io/balena-cli/issues/2292

SSH access docs: Replace 'balena ssh' with 'ssh' when used with 'tunnel'

---

tools/fetch-external.sh

This prevents link-checker from trying to validate markdown files
that are not published.
---

Remove shared pages that have had relevant sections extracted already

---

tools/fetch-external.sh

Should not be merged until https://github.com/balena-io/balena-cli/pull/2388 merged.
Signed-off-by: Scott Lowe <scott@balena.io>

Update CLI docs source URL inline with landr related changes

---

shared/general/deviceTypeNames.md

See: https://jel.ly.fish/support-thread-documentation-need-updated-amd64-genericx86-64-ext-1b5828a
Signed-off-by: Andrea Rosci <andrear@balena.io>
---

Add missing genericx86-64-ext device type

---

pages/learn/deploy/delta.md

Clarified deltas default enabled behavior can't be disabled on devices above balenaOS 2.47.1
﻿Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>
---

patch: Clarify deltas default behavior

---

config/navigation.txt
config/redirects.txt
pages/learn/manage/configuration.md
pages/reference/OS/advanced.md
pages/reference/supervisor/configuration-list.md
shared/general/config-variables-pi.md
templates/_base-images-ref.html
templates/_config.html
templates/_devices.html
templates/_machines-architectures.html
templates/config.html
templates/default.html

- Add a new page for the configuration list with a dropdown menu for device types
- Parsing API response to generate a table with some description
- Add page to the /reference/supervisor section
- Redirected to raspberrypi3's configuration list as the default device type
TODO

Automate configuration list through balena API

---

pages/reference/OS/advanced.md

patch: Clarify quotes when setting dtoverlay

---

.github/workflows/link-checker.yml

Lychee's Github action 1.2.0 fails to parse markdown files, hence reverting back. 
Related: 
https://github.com/lycheeverse/lychee/issues/436
https://github.com/lycheeverse/lychee-action/issues/67
Reverts balena-io/docs#2156

Revert "patch: bump lycheeverse/lychee-action from 1.1.1 to 1.2.0"

---

pages/reference/base-images/base-images.md

Includes a link to an example base image Dockerfile named by device type, which shows the extra tools included.
My goal simply is to call out the practical relationship between base images based on device type vs. architecture. So the change in this PR is in the [Image Names section](https://www.balena.io/docs/reference/base-images/base-images/#image-names), where the use of device type or architecture for the name is introduced. Replaces #2150, which changed the [How to Pick a Base Image section](https://www.balena.io/docs/reference/base-images/base-images/#how-to-pick-a-base-image), which has a wider scope that did not fit the goal as well.

Note how base images named with device type extend those named with architecture

---

pages/reference/OS/advanced.md
templates/config.html

This came from a particular set of changes to config.txt file
on a Raspberry Pi making the device not boot but the problem is general
enough to apply to all devices. There are many ways of misconfiguring
the variables to make the system not bootable, certainly more that we
would be able to list in the docs, therefore the suggestion is to try
in a controlled environment before rolling to production.
---

Be more explicit about risks of using advanced configuration variables

---

shared/network/2.x.md

Based on discussion in brainstorm topic (internal only):
https://jel.ly.fish/brainstorm-topic-c3f8670a-8981-42ae-bcbf-1f57e959122d
Copied from this pattern (internal only):
https://jel.ly.fish/scratchpad-entry-0b610300-4182-4627-83b6-90ae82e9661c

network/2.x: Add instructions to disable IPv6 if required

---

shared/overview/2.x.md

BalenaOS is now a unified image that can be configured for production
or development mode. Update the documentation to reflect this.
Signed-off-by: Alex Gonzalez <alexg@balena.io>
---

overview: 2.x: Remove mentions to OS variants

---

config/dictionaries/resource.json

This only made any sense within the context of the device or the vpn
server and there are much better ways of handling it for the past 6+
years
---

Remove vpn_address from resource.json as it is not useful

---

pages/learn/getting-started.md

Noticed projects URL in "Next steps" section returns a 404. Looks like correct one is just a single character change.

patch: Fix link to projects

---

templates/_track.html

Fix for "When querystring is present the page was reloading infinitely".
https://github.com/balena-io/docs/issues/1935

patch: fix querystring infinite reload

---

pages/learn/manage/device-logs.md

The great migration of masterclasses begins now. 
Context: https://www.flowdock.com/app/rulemotion/i-docs/messages/46759
---

minor: Add further context on device logging from  masterclasses

---

pages/reference/base-images/base-images.md
pages/reference/sdk/deprecation-policy.md

With #2228, we upgraded MetalSmith to v2.4.2, which included the following change https://github.com/metalsmith/metalsmith/issues/226 
We had two instances of the invalid Frontmatter that MetalSmith didn't complain about until now. I removed those 2 instances in this PR since there weren't hugely impactful. Here's the error that were seeing below on build time:
---

patch: Resolve invalid frontmatter errors

---

.github/workflows/deploy-to-heroku.yml

Automatic deployments using Heroku-Github Oauth integration
is currently broken.
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>
---

Add Github action to automatically deploy to Heroku.

---

.github/workflows/link-checker.yml

The Github action wasn't working or creating issues since the directory name was wrong.
---

patch: Fix directory name in GitHub Action

---

config/navigation.txt
pages/reference/OS/network.md

The os_version keys were deleted in the previous PR. These were still referenced in the documentation and not removed. I have removed them now. The error we were seeing on build time. 
```
Expanding dynamic doc reference/supervisor/configuration-list.md
Parsing navigation...
/home/vipulgupta2048/work/docs/node_modules/@balena/doxx/doxx.js:16
throw err
^
Error: Unknown key $os_version
at /home/vipulgupta2048/work/docs/node_modules/metalsmith-dynamic/build/dictionaries.js:67:13
at Dicts.getDict (/home/vipulgupta2048/work/docs/node_modules/metalsmith-dynamic/build/dictionaries.js:68:7)
at Dicts.getValues (/home/vipulgupta2048/work/docs/node_modules/metalsmith-dynamic/build/dictionaries.js:72:23)
at setRefRec (/home/vipulgupta2048/work/docs/node_modules/@balena/doxx/build/metalsmith-plugins.js …
```

patch: Remove $os_version key from docs

---

config/redirects.txt
pages/reference/OS/network.md

~Redirect 1.x balenaOS docs to 2.x~
Update: Will be redirecting both 1.x and 2.x balenaOS docs to just the page, not keep it version specific. This is because we deprecated all balenaOS 1.x docs and the only major version that remains is 2.x. Hence it make sense to drop the version specific docs entirely. Examples:
1. https://www.balena.io/docs/reference/OS/overview/2.x/ --> https://www.balena.io/docs/reference/OS/overview/
2. https://www.balena.io/docs/reference/OS/network/1.x/ --> https://www.balena.io/docs/reference/OS/network/
Context: https://www.flowdock.com/app/rulemotion/resin-devops/threads/hQm7r4VFlyTyeKS2PE6yXRNrcUo
---
> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTR …

patch: Redirect deprecated docs

---

config/index.coffee

With #2280, I didn't take into account deleting these items from the list of dynamic pages. Both these pages are no longer dynamic, and hence can be removed from here. This field is used to generate "Improve this Doc" links for the docs.
---

patch: Fix Doc improvement links for balenaOS Overview & Network page

---

pages/reference/OS/extended-support-release.md

Also, add the RockPi 4B to the list of ESR supported devices.
Fixes #2295
Signed-off-by: Alex Gonzalez <alexg@balena.io>
---

extended-support-release: Update to semver versioning

---

tools/build.sh

The doxx command in the build script used to error out with an exit code 0. This PR fixes that behavior with converting the unhandled-rejections in node to strict which makes sure `unhandledpromiserejection` errors always exit the program with exit code 1. Also, added `set -e` along with other bash environment variables to improve script's behavior overall. 
This primarily makes sure our CI/CD builds won't be successfull if the docs build is failing. Hopefully preventing us from merging broken documentation changes. 
Context: https://www.flowdock.com/app/rulemotion/resin-devops/threads/lRgvlRyPy6MLl4c5dsgI-vVbnEw
---
> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) …

patch: Fail build script when doxx command errors out

---

pages/learn/develop/hardware/i2c-and-spi.md

uart_mode on the iot-gate-imx8 will be managed by the supervisor once https://github.com/balena-os/balena-supervisor/issues/1948 is implemented
---

develop/hardware: Add IOT-GATE-iMX8 uart mode instructions

---

pages/learn/develop/cloud-iot-provisioning.md

Simple fix for an oversight in the final Cloud IoT Provisioning dynamic page. I also verified that there were not any other missing keys.

Fix reference to missing dictionary key in Cloud IoT Provisioning

---

tools/extract-markdown.sh
tools/fetch-external.sh
tools/prepare.sh
tools/test-spelling.sh

`#!/usr/bin/env` searches PATH for bash, and bash is not always
in /bin, particularly on non-Linux systems.
---

patch: Replace shebang in scripts with env interpreter

---

pages/reference/supervisor/docker-compose.md

Occasionally users try to use fields that are supported by v2 but have
different properties in version 3 (like long syntax for ports) and
are surprised to get an error in response.
Clarify that our support is based on version 2.4
Signed-off-by: Robert Günzler <robertg@balena.io>

Update compose file docs

---

pages/learn/manage/device-logs.md

The docs previously said persistent logs were stored at
"`/var/log/journal/<uuid>` where the UUID is device UUID". In fact, the
UUID used in this path is not related with the device UUID: it comes
from the "machine ID" (found at `/etc/machine-id`) that is generated by
Systemd during the first boot.
Resolves #2355

Fix location of persistent logs

---

.github/workflows/deploy-to-heroku.yml

@rhampt brought it to our attention that docs are actually not being deployed even though we took action to run a Heroku GitHub Action daily in order to keep the external references updated. I checked it out, and each day the jobs end with "Everything up to date" since docs doesn't have many patches coming daily. 
Hence, we need to rebuild the Heroku app everyday and I think this is solution for the same. 
---

patch: Force Heroku to rebuild docs daily

---

config/doxx.coffee
config/index.coffee
config/links.coffee

Had a thought about this. Our overall goal is remove as many static paritals as we could for our dynamic docs. The newest edition to Dyanmic docs is the Cloud Provisioning docs that doesn't use partials at all. Hence, I am putting together this patch to deprecate the dynamic docs proprety completely. This benefits two-folds
1. No more confusion on where the "Improve this doc" link will point to 
2. With no partials to point to, we can point to the main blueprint doc as the improve this doc link
Additionally fixes issues with "Improve this Doc" links for Cloud Provisioning docs since they don't have any partials. Their improve link was going 404
---
> *Please make sure to read the …

patch: Deprecate Dynamic Docs config option

---

config/dictionaries/resource.json
templates/api.html

Added 2 examples explaining how balenaOS can be downloaded using the /download endpoint for both public and private device types. This is how it looks. 
---

patch: Add docs for download endpoint

---

pages/faq/troubleshooting/troubleshooting.md

Updated broken URL to one that's more likely to stay valid, and added extra guidance to help find the resource, in case the website changes.

Fix PIP link, make more robust.

---

.github/workflows/deploy-to-heroku.yml

Mysteriously our scheduled GitHub action workflow to update the website has stopped running. I checked the logs and recent commits to find potenial errors. It stopped running on the scheduled time for 5 days. Checking answers on the web, I found folks suggesting way to unclog the run queue to get the scheduled action running again along with a way to trigger it manually to get it running. 
1. https://stackoverflow.com/questions/59560214/github-action-works-on-push-but-not-scheduled
2. Scheduled workflows are unreliable https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working/
3. Adding a manual trigger seems a nice way to unblock when we are in a fix: https://devopsjournal.io/blog/2022/08/12/workflows-not-starting
Will give this a shot and see if it fixes it. …

patch: Add support for manaul workflow runs

---

pages/learn/develop/hardware/i2c-and-spi.md

... that support custom device-tree loading.
---

develop/hardware: Add Jetson AGX Orin to the list of devices

---

pages/learn/deploy/deployment.md
shared/deployment/secrets/_default.md

Clarify balena deploy's build time secrets limitation is only for files

---

pages/reference/supervisor/docker-compose.md

`network_mode: service:[service name]` has been supported since Supervisor v10.1.0.
Signed-off-by: Christina Ying Wang <christina@balena.io>
---

Update supported network_mode

---

.github/workflows/link-checker.yml
lychee.toml

Adds in an extra degree of checking if external resource URL's are not failing. 
---

Add fetch-external script to link checker

---

pages/reference/OS/network.md

The fix is for a link to NetworkManager docs for the connectivity check. The link was using Debian Jessie docs that are missing a lot of guidance on the check. Unfortunately the canonical docs do not use a stable name for the HTML anchor, so must advise the reader how to search for the section within that page.

Update obsolete link

---

pages/reference/supervisor/bandwidth-reduction.md

Emphasize bandwidth used per feature, and simplify. Also add the effect of NetworkManager connectivity check.

Revise bandwidth reduction page with cellular measurements

---

.github/workflows/deploy-to-cloudflare-pages.yml
.github/workflows/flowzone.yml

Scheduling Flowzone didn't and won't work out since: https://balena.zulipchat.com/#narrow/stream/348930-balena-io.2Fflowzone/topic/.E2.9C.94.20Flowzone.20on.20schedule.20jobs
Hence, this PR reverts #2551 and adds a custom action to deploy to CF pages daily.
---

patch: Deploy daily to Cloudflare using custom action

---

pages/reference/OS/overview.md

I wasn't clear if the [sentence](https://docs.balena.io/reference/OS/overview/#hostname) says "\<short-UUID\>.local" is the default Avahi network domain name broadcast or the default device hostname. Since the paragraph is focused on hostname, define the default hostname, not the broadcast name.
For [reference](https://github.com/balena-os/meta-balena/blob/master/meta-balena-common/recipes-support/balena-hostname/balena-hostname/balena-hostname), see how hostname is set at boot time.

Clarify default value for device hostname

---

pages/learn/manage/device-logs.md

A user reached out to us informing that logs size increase does work in production: https://github.com/balena-io/docs/pull/2263#issuecomment-1470809925
In this PR, I removed the variant clarification and added a gentle warning for folks changing their configurations. 
---

patch: Clarify variant for increasing size of persistent logs store

---

config/dictionaries/cloud.json
pages/learn/develop/cloud-iot-provisioning.md

We have added support to [Cloud Relay](https://github.com/balena-io-examples/cloud-relay) for ClearBlade's IoT Core service on Google Cloud as a replacement for Google's deprecated IoT Core. This PR documents how to use it.
Significant changes:
* Add `platformName` to cloud dictionary; need to distinguish platorm from IoT Core service for ClearBlade-GCP hybrid
* Add paragraph to top section to describe relationship between ClearBlade and GCP; also mention deprecation and migration blog post
* Add link to ClearBlade-GCP from GCP IoT Core page

Add ClearBlade-GCP selection to cloud IoT provisioning page

---

shared/troubleshooting/raspberrypi3-64.md
shared/troubleshooting/raspberrypi3.md

[v2.89.19](https://github.com/balena-os/balena-raspberrypi/commit/8b6f572f94fc01ac20709a2d03358f386734c36f) updated the rpi bootfiles to 2022.01.20 in https://github.com/balena-os/balena-raspberrypi/commit/eab45104bc657d5ab5a0c4c539f3d1569945d7f2
Therefore, the RasberryPi 3B+ R9 should be usable according to the [PCN](https://pip.raspberrypi.com/categories/797-pcn/documents/RP-003337-PC/Pi3B-Revision-9-PCN.pdf), with BalenaOS releases newer than [v2.89.19](https://github.com/balena-os/balena-raspberrypi/commits/master?after=49dd0694d19fd0010002f5df85c2535703555962+419&branch=master&qualified_name=refs%2Fheads%2Fmaster)
---
> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for …

docs/troubleshooting: Update RPI 3B+ hw revisions info

---

.cspell/balena-words.txt
pages/learn/manage/actions.md

The device deactivation fee has been documented under the FAQ section on our billing page but there wasn't any mention of it in the docs. This PR fixes that. 
Context: https://balena.zulipchat.com/#narrow/stream/350505-aspect.2Fmarketing/topic/Docs.20-.20Deactivation.20Fee
---

patch: Add deactivation fee to device deactivate feature

---

config/dictionaries/resource.json

As [discussed internally](https://balena.zulipchat.com/#narrow/stream/345882-_help/topic/device.2Eoverall_status/near/362024508), the `overall_status` field was missing for the `device` resource.
First time touching the API resources part of the docs. [Looks correct](https://38e5a981.balenacloud-docs.pages.dev/reference/api/resources/device/), but let me know if I did something wrong here!

Add the `overall_status` field for `device`

---

config/redirects.txt

Redirecting the Getting Started guide to show RPi5

patch: Getting Started to default show Raspberry Pi 5

---

pages/learn/deploy/offline-updates.md

The `balena fleet` commands in this guide no longer work with the latest version of the CLI which returns a capitalized table instead of all uppercase items. Not sure when this change took place on the CLI side. 

Update commands in offline updates

---

config/dictionaries/cloud.json
config/redirects.txt
pages/learn/develop/cloud-iot-provisioning.md

Google's Cloud IoT service was terminated in mid-August 2023. This update removes references to it from the Cloud IoT provisioning section.

Remove references to defunct Google Cloud IoT service

---

pages/learn/manage/device-logs.md

More generally, make it clear that changes to journald-balena-os.conf will be overwriten by balenaOS updates.
@vipulgupta2048 , please see what you think. This clarification is motivated by [a support ticket](https://jel.ly.fish/support-thread-1-0-0-front-cnv-es87j7x).

Explain that changes to the persistent log size are not persistent

---

pages/learn/manage/actions.md

See: https://balena.fibery.io/Inputs/Pattern/user-expected-device-deactivation-fee-to-be-covered-by-their-plan's-allowance-4579
See: https://balena.zulipchat.com/#narrow/stream/346009-aspect.2Fcustomer-success/topic/tpsistemas.20querying.20about.20a.20bill.20over.20deactivated.20devices/near/408236452
---

actions.md: Clarify that the deactivation fee is not covered by the plan's allowance

---

.cspell/computer-terms.txt
static/css/cookie-consent.css
static/scripts/main.js
templates/_track.html
templates/default.html

Adding Cookie Consent dialog box to the docs for customers to choose between their cookie preferences. 
Pull request also includes updated analytics client and new GTM container

minor: Add Cookie Consent Dialog box

---

templates/_base-images-ref.html
templates/_config.html
templates/_copy_code_block.html
templates/_devices.html
templates/_esr_devices.html
templates/_machines-architectures.html

Adding Subresource integrity to script tags in the docs. 
Hash generated from: https://www.srihash.org/
Report: https://github.com/balena-io/docs/security/code-scanning/1
Solves: https://github.com/balena-io/docs/issues/2909

patch: Add Subresource Integrity to scripts being fetched

---

config/dictionaries/resource.json

API/Resources: Add docs for the `device type` resource

---

pages/reference/OS/advanced.md

Supervisor v16+ adds each dtparam for a dtoverlay on its own line to comply with the 80-char line limit for config.txt.

Update config.txt to reflect changes in config.txt parsing with Supervisor v16+

---

.github/workflows/link-checker.yml

Saw a large uptick in failed GitHub Actions, hence adding in the token to make sure it all works. 

patch: Add token input to lychee action

---

config/dictionaries/resource.json

Since these do not use the release_tags for picking the versions, I've put this as draft and merge it after https://github.com/balena-io/balena-api/pull/4821 gets released, which bacfills the semver fields of all releases from their release_tags, so that users don't get  confused by the v0.0.0 versions.
Depends-on: https://github.com/balena-io/balena-api/pull/4821
See: https://balena.zulipchat.com/#narrow/stream/345889-balena-io.2Fos/topic/Determine.20list.20of.20supported.20OS.28hostapp.29.20for.20a.20device-type/near/421801181
---

API/Resources: Add docs listing the balenaOS versions of a device type

---

config/navigation.txt
tools/build-masterclass.sh
tools/fetch-external.sh

Makes necessary changes to account for seperate docs for supervisor-state and device diagnostics not existing
---

Stop pulling diagnosis sub docs

---

pages/reference/OS/network.md

The old network-manager has been deprecated and the links needs to be replaced.

patch: Update network-manager links from developer-old.gnome.org

---

.cspell/balena-words.txt
CONTRIBUTING.md
pages/learn/more/glossary.md

Remove outdated references to versionbot

---

lychee.toml

patch: Fix broken links

---

.github/workflows/flowzone.yml
.github/workflows/link-checker.yml
lychee.toml

Use Lychee to check the following links 
1. During a pull request, Flowzone will publish the staging version of the site to CF, use the CF url to check links (with cache)
2. During a scheduled run, use the production url, docs.balena.io to check any links broken (without cache) 

patch: Check links on staging deployments

---

.gitignore
pages/reference/base-images/base-images.md
tools/build-base-images.sh
tools/build.sh

This change generates versions for base images stacks
- **patch: Generate base images stack versions automatically**
- **Add base images generation script to build process**
After:
Fibery: https://balena.fibery.io/Work/Project/Automate-base-images-public-docs-202

Generate base images stack versions

---

config/navigation.txt
config/redirects.txt
pages/faq/questions.md
pages/learn/deploy/build-optimization.md
pages/learn/develop/dockerfile.md
pages/learn/develop/hardware.md
pages/learn/develop/runtime.md
pages/reference/OS/network.md
pages/reference/base-images/balena-base-images.md

Same reasoning and project as #3062
- **patch: Rename base-images.md to balena-base-images.md**
- **Fix links for balena-base-images page**
- **Add redirects & navigation entry**

Reduce repetitive paths for base-images docs

---

pages/learn/deploy/release-strategy/update-strategies.md
pages/learn/getting-started.md
pages/learn/more/glossary.md
pages/reference/supervisor/configuration-list.md
shared/getting-started/whatYouNeed/fincm3.md
shared/troubleshooting/jetson-nano-2gb-devkit.md
shared/troubleshooting/jetson-nano-emmc.md
shared/troubleshooting/jetson-nano.md
shared/troubleshooting/jetson-tx2-nx-devkit.md
shared/troubleshooting/jetson-tx2.md
templates/default.html

Pages which have page titles over Google's estimated pixel length limit for titles in search results. Google snippet length is actually based upon pixels limits, rather than a character length. The SEO Spider tries to match the latest pixel truncation points in the SERPs, but it is an approximation and Google adjusts them frequently.
Pages which have h1s over the configured length. There is no hard limit for characters in an h1, however they should be clear and concise for users and long headings might be less helpful

patch: Reduce title text to 70 characters

---

pages/learn/accounts/idp-setup/google-workspace-saml-setup.md

Fix SAML docs use `auth` prefix on SAML urls

---

pages/reference/api/overview.md

See: https://balena.fibery.io/Work/Task/Update-the-doc-examples-to-use-the-v7-model-2208

API/overview: Replace the application.device_type property with is_for__device_type since it's not in the v6 model

---

pages/reference/hardware/wifi-dongles.md

Add a disclaimer to the Supported Wifi Modems sections, to make clear that the tests we are executing are limited to a few things, and not for complete modem + board testing
---

patch: add tested modem disclaimer

---

pages/reference/api/overview.md

Firstly $any can also be used for filtering using
reverse navigation resources as well, while
the previous approach works only for FKs.
On top of that filtering using $any is also
faster.

API/overview: Change the associated resource $filter example to use $any & apply on the slug field

---

config/dictionaries/resource.json

That's in order to make the v7 PR smaller
See: https://balena.fibery.io/Work/Task/API-resources-Move-the-balenaOS-releases-examples-next-to-the-Release-examples-2256
---

API/resources: Move the balenaOS releases examples next to the Release examples

---

pages/reference/api/overview.md

This should have been part of #3093
See: https://balena.fibery.io/Work/Task/API-resources-Change-the-requests-to-use-the-v7-endpoint-2258
---

API/overview: Update the requests to use the v7 endpoint

---

package-lock.json
package.json

Update balena-SDK to the latest primarily to have Jetson provisioning instructions that point to the updated Jetson Flash tool in the Getting Started guide. Getting Started guide for Jetson Nano to prove things work.
Link: https://cb9417a5.balenacloud-docs.pages.dev/learn/getting-started/jetson-nano/nodejs/#provision-device
Context: https://balena.zulipchat.com/#narrow/channel/350505-aspect.2Fgrowth/topic/Improving.20Jetson-flash.20documentation

Update NPM packages for latest Getting Started instructions

---

.cspell/balena-words.txt
.gitignore
config/navigation.txt
config/redirects.txt
pages/reference/sdk/node-sdk.md
pages/reference/sdk/python-sdk.md
templates/balena-sdk-python.html
tools/build.sh
tools/fetch-external.sh
tools/versioning.js

Create versioned docs for Python SDK

Create versioned docs for Python SDK

---

pages/reference/supervisor/docker-compose.md

Currently we don't support using `env_file` top-level or `service.env_file` attributes, so clarify this in the docker-compose docs.

Specify env_file attribute as unsupported

---

pages/reference/OS/updates/update-process.md

Restructure Update Process page to include Standard HUP and Advanced HUP

Add Advanced HUP and update existing HUP docs

---

.cspell/computer-terms.txt
pages/learn/develop/hardware/i2c-and-spi.md

... for Jetson Orin devices running Jetpack 6
---

pages/learn: Add fan profile and power mode information

---

pages/reference/OS/updates/update-process.md

Reverts balena-io/docs#3115
Feature unreleased: documentation to be deployed when feature is released. 
Context: https://balena.zulipchat.com/#narrow/channel/346007-balena-io.2FbalenaCloud/topic/takeover.20x.20Jetson.20Xavier.20JP4-.3EJP5.20on.20balenaCloud

Revert "Add Advanced HUP and update existing HUP docs"

---

.github/workflows/link-checker.yml

v4 of this action has been failing for the past few weeks with the error: `Resource not accessible by integration`
---

patch: Update create-issue-from-file action to v5

---

.github/workflows/flowzone.yml
package-lock.json
package.json

Contains an additional change to resolve failing CI checks about `env` not being in context of `args`
I used this way of passing the env variable to get it into context. 
---

patch: Update NPM dependencies

---

pages/reference/hardware/wifi-dongles.md
tools/fetch-external.sh

The list of supported wifi dongles and modems is out of date and sets an uneralistic expectation for hardware compatibility - its better to remove this until we actually have a proper modem story
Supersedes https://github.com/balena-io/docs/pull/2193 if we go with this
---

reference/wifi-dongles.md: Remove list of supported modems

---

pages/learn/develop/hardware/gpio.md

Intel Edison has been deprecated a long time ago.

minor: remove edison from gpio.md

---

pages/reference/api/overview.md

Added a section on rate limiting to our API docs so that customers can understand why we don't publish our rate limits.
---

patch: Updated API docs regarding rate limiting

---

pages/learn/develop/local-mode.md
shared/general/container-ssh.md

Updated all instances of `{{ $names.company.short }}` commands to use the renamed versions using https://github.com/balena-io/balena-cli/blob/v20.2.1/docs/balena-cli.md as reference

patch: update to `balena device <subcommand>`

---

pages/learn/develop/hardware/i2c-and-spi.md

Edison was EOL'd years ago, so these docs are just bloat
---

patch: Remove Edison hardware docs

---

pages/learn/getting-started.md

Deprecated command `fleets` replaced by `fleet list`
---

Replace deprecated command `fleets` to `fleet list`

---

shared/jetson-orin/jetson-orin-nano-seeed-j3010.md
shared/jetson-orin/jetson-orin-nx-seeed-j4012.md
shared/jetson-orin/jetson-orin-nx-xavier-nx-devkit.md

These three Orin devices used to have common instructions, but now that they have individual pages, we can specify their slugs directly in the instructions.
---

shared/jetson-orin: Specify device-type slugs for Seeed and Orin NX
